"""ATLAS Execution Models - Order request/response and fill structures."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import uuid


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    LIMIT = "limit"
    MARKET = "market"


class OrderStatus(str, Enum):
    OPEN = "open"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class TimeInForce(str, Enum):
    GTC = "GTC"  # Good Till Cancelled
    IOC = "IOC"  # Immediate Or Cancel
    FOK = "FOK"  # Fill Or Kill


@dataclass(slots=True, frozen=True)
class OrderRequest:
    """Immutable order request - generated by StrategyEngine."""
    symbol: str
    side: OrderSide
    type: OrderType
    amount: float
    price: Optional[float] = None
    time_in_force: TimeInForce = TimeInForce.GTC
    exchange: str = ""
    strategy_id: str = ""
    metadata: dict = field(default_factory=dict)
    idempotency_key: str = field(default_factory=lambda: str(uuid.uuid4()))


@dataclass(slots=True, frozen=True)
class OrderResponse:
    """Normalized order response from exchange."""
    exchange_order_id: str
    client_order_id: str  # = idempotency_key
    symbol: str
    side: OrderSide
    type: OrderType
    amount: float
    price: Optional[float]
    filled: float
    status: OrderStatus
    timestamp: int
    exchange: str
    fee: float = 0.0
    fee_currency: str = ""


@dataclass(slots=True, frozen=True)
class CancelResponse:
    """Order cancellation response."""
    exchange_order_id: str
    client_order_id: str
    success: bool
    status: OrderStatus
    timestamp: int
    exchange: str


@dataclass(slots=True, frozen=True)
class Fill:
    """Single fill (partial or full execution)."""
    order_id: str
    fill_id: str
    price: float
    amount: float
    fee: float
    fee_currency: str
    timestamp: int
    side: str  # "buy" or "sell"
