"""
Liquidity-Scaled Mean Reversion with Adaptive Regime eXtra (LSMR-ARX)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1).

WHY DISTINCT from every prior auto-gen family:
  Prior families: grid geometry (ATR/z-score/ISV), trend-slope scalpers (VWMR,
  Chandelier), cycle-decomposition (CPAGrid), order-flow/exhaustion, Hurst
  regime-switch (HARS), gravity/value-anchored.
  LSMR-ARX introduces a NEW axis the fleet has never parameterized: ORDER-BOOK
  LIQUIDITY-SCALED grid geometry. Instead of spacing being only a function of
  price/vol, it is updated live from the top-of-book imbalance and depth so the
  grid compacts where liquidity is deep (tighter ticks are cheap to fill) and
  widens where liquidity is thin (avoid being the liquidity provider in a thin
  book). Combined with a dual ATR/Hurst regime gate that flips the inner grid
  to a breakout overlay.

KEY IDEA:
  - Maintain a streaming EWM volatility (ATR proxy) and a streaming Hurst-like
    trend index (scaled R/S on a bounded sliding window, no giant arrays).
  - On each tick, compute bid/ask depth if provided; derive an imbalance score
    in [-1, +1] and a depth-normalized liquidity factor in (0, 2].
  - Base spacing = k * ATR * liquidity_scale; liquidity_scale shrinks spacing
    when depth is deep and widens when thin. Grid is re-centred toward the
    liquidity-weighted mid when imbalance is extreme (avoid fighting a wall).
  - Regime gate: if Hurst > h_high (trending), disable mean-reversion on the
    core grid and activate a momentum breakout overlay on the outer band.
  - Position sizing is volatility-targeted and liquidity-capped (never post an
    order larger than a configurable fraction of observed depth).

OOM SAFETY:
  All rolling stats are streaming (bounded deques + Kahan compensated sum).
  No unbounded lists, no list comprehension over candle streams, explicit
  `del` on resize + `gc.collect()` where a batch window is regenerated.
  estimate_memory_mb() is O(1) and config-driven.

CONFIG:
  ---
  strategy: LSMR-ARX
  symbol: SOL/EUR
  capital: 13.5
  atr_window: 24
  atr_k: 1.8
  hurst_window: 48
  hurst_high: 0.60
  hurst_low: 0.45
  depth_window: 40
  max_depth_scale: 2.0
  min_depth_scale: 0.6
  max_imbalance_shift: 0.35
  vol_target: 0.02
  vol_smoothing: 0.1
  max_liquidity_fill_pct: 0.20
  max_trades: 40
  ---
"""

from __future__ import annotations

import gc
import math
from collections import deque
from typing import Any, Deque, Dict, Optional, Tuple


# --------------------------------------------------------------------------- #
# Strategy protocol (mirror of denaro node's StrategyBase)
# --------------------------------------------------------------------------- #
class StrategyBase:
    """Minimal interface contract. Real nodes subclass StrategyBase from the
    denaro engine; this module ships a standalone reference so it can be
    tested and reviewed in isolation and later dropped in with zero imports."""

    def on_tick(self, tick: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        raise NotImplementedError

    def on_fill(self, fill: Dict[str, Any]) -> None:
        raise NotImplementedError

    def validate_config(self, cfg: Dict[str, Any]) -> None:
        raise NotImplementedError

    def estimate_memory_mb(self, cfg: Dict[str, Any]) -> float:
        raise NotImplementedError


# --------------------------------------------------------------------------- #
# Streaming momentum / volatility primitives (all O(1) per push)
# --------------------------------------------------------------------------- #
class _KahanEwma:
    """Exponentially-weighted moving average with Kahan compensated summation
    to keep numerical drift bounded on long candle streams."""

    __slots__ = ("alpha", "mean", "_comp", "n")

    def __init__(self, alpha: float) -> None:
        self.alpha = float(alpha)
        self.mean: float = 0.0
        self._comp: float = 0.0
        self.n: int = 0

    def push(self, x: float) -> None:
        self.n += 1
        if self.n == 1:
            self.mean = float(x)
            return
        raw: float = self.mean + (float(x) - self.mean) * self.alpha
        # Kahan compensation for the update term.
        y: float = float(x) - self._comp
        self.mean = raw
        self._comp = (raw + y) - self.mean


class _RingStats:
    """Bounded sliding window with O(1) mean and population variance via
    Welford's online algorithm. Deliberately bounded: resizing is explicit."""

    __slots__ = ("maxlen", "buf", "_m2", "_mean", "_n")

    def __init__(self, maxlen: int) -> None:
        self.maxlen = int(maxlen)
        self.buf: Deque[float] = deque(maxlen=self.maxlen)
        self._m2: float = 0.0
        self._mean: float = 0.0
        self._n: int = 0

    def push(self, x: float) -> None:
        if self._n >= self.maxlen:
            # Remove oldest to keep online aggregates consistent.
            oldest: float = self.buf[0]
            self.buf.popleft()
            self._n -= 1
            if self._n == 0:
                self._m2 = 0.0
                self._mean = 0.0
            else:
                new_mean: float = (
                    self._mean * (self._n + 1) - oldest
                ) / self._n
                self._m2 = self._m2 - (oldest - new_mean) * (
                    oldest - self._mean
                )
                self._mean = new_mean
        # Welford insertion.
        self.buf.append(float(x))
        self._n += 1
        if self._n == 1:
            self._mean = float(x)
            self._m2 = 0.0
            return
        delta: float = float(x) - self._mean
        self._mean += delta / self._n
        self._m2 += delta * (float(x) - self._mean)

    @property
    def mean(self) -> float:
        return self._mean

    @property
    def variance(self) -> float:
        return self._m2 / self._n if self._n > 1 else 0.0

    @property
    def std(self) -> float:
        return math.sqrt(self.variance)

    @property
    def count(self) -> int:
        return self._n

    def clear(self) -> None:
        self.buf.clear()
        self._m2 = 0.0
        self._mean = 0.0
        self._n = 0


# --------------------------------------------------------------------------- #
# Strategy
# --------------------------------------------------------------------------- #
class LSMR_ARX(StrategyBase):
    """Liquidity-Scaled Mean Reversion with Adaptive Regime eXtra."""

    # Default configuration, overridable via validate_config()/config dict.
    DEFAULTS: Dict[str, Any] = {
        "capital": 100.0,
        "atr_window": 24,
        "atr_k": 1.8,
        "hurst_window": 48,
        "hurst_high": 0.60,
        "hurst_low": 0.45,
        "depth_window": 40,
        "max_depth_scale": 2.0,
        "min_depth_scale": 0.6,
        "max_imbalance_shift": 0.35,
        "vol_target": 0.02,
        "vol_smoothing": 0.1,
        "max_liquidity_fill_pct": 0.20,
        "max_trades": 40,
        "risk_per_trade": 0.01,
    }

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        cfg: Dict[str, Any] = dict(self.DEFAULTS)
        if config:
            cfg.update(config)
        self.validate_config(cfg)
        self.cfg: Dict[str, Any] = cfg

        # Streaming state.
        self.price: float = 0.0
        self.last_price: Optional[float] = None
        self.atr_ewma = _KahanEwma(1.0 / float(cfg["atr_window"]))
        self.returns = deque(maxlen=max(int(cfg["hurst_window"]), 4))
        self.depth_series = _RingStats(int(cfg["depth_window"]))
        self.hurst_index: float = 0.5
        self.liquidity_scale: float = 1.0
        self.imbalance: float = 0.0

        # Grid bookkeeping.
        self.orders: Dict[str, Dict[str, Any]] = {}
        self.trade_count: int = 0
        self.realized_pnl: float = 0.0
        self.position: float = 0.0
        self.entry_price: Optional[float] = None

    # ---- config ---------------------------------------------------------- #
    def validate_config(self, cfg: Dict[str, Any]) -> None:
        """Raise ValueError on any invalid or contradictory config value."""
        if float(cfg.get("capital", self.DEFAULTS["capital"])) < 1.0:
            raise ValueError("capital must be >= 1.0")
        if int(cfg.get("atr_window", self.DEFAULTS["atr_window"])) < 5:
            raise ValueError("atr_window must be >= 5")
        if int(cfg.get("hurst_window", self.DEFAULTS["hurst_window"])) < 16:
            raise ValueError("hurst_window must be >= 16")
        high: float = float(cfg.get("hurst_high", self.DEFAULTS["hurst_high"]))
        low: float = float(cfg.get("hurst_low", self.DEFAULTS["hurst_low"]))
        if high <= low:
            raise ValueError("hurst_high must be > hurst_low")
        if float(cfg.get("max_depth_scale", 2.0)) <= float(
            cfg.get("min_depth_scale", 0.6)
        ):
            raise ValueError("max_depth_scale must be > min_depth_scale")
        if not (0.0 < float(cfg.get("vol_target", 0.02)) <= 0.5):
            raise ValueError("vol_target must be in (0, 0.5]")
        if int(cfg.get("max_trades", 40)) < 1:
            raise ValueError("max_trades must be >= 1")

    def estimate_memory_mb(self, cfg: Any = None) -> float:
        """O(1) memory estimate driven by config window sizes."""
        c: Dict[str, Any] = dict(self.DEFAULTS)
        if isinstance(cfg, dict):
            c.update(cfg)
        # Bounded deques/ring buffer: ~16 bytes/float × window entries.
        floats: int = (
            int(c["hurst_window"]) + int(c["atr_window"]) + int(c["depth_window"])
        )
        base_mb: float = floats * 16 / (1024 * 1024) + 0.15
        # Orders dict: small bounded overhead.
        orders_mb: float = int(c["max_trades"]) * 0.0002
        return round(base_mb + orders_mb, 3)

    # ---- private helpers ------------------------------------------------- #
    def _update_hurst(self) -> None:
        """Streaming Hurst-like trend index using scaled R/S on bounded window."""
        n: int = len(self.returns)
        if n < 8:
            self.hurst_index = 0.5
            return
        vals: list = list(self.returns)
        mean_r: float = sum(vals) / len(vals)
        cumdev: float = 0.0
        r_max: float = 0.0
        r_min: float = 0.0
        for v in vals:
            cumdev += v - mean_r
            if cumdev > r_max:
                r_max = cumdev
            if cumdev < r_min:
                r_min = cumdev
        r: float = r_max - r_min
        s: float = sum((v - mean_r) ** 2 for v in vals) / (len(vals) - 1)
        std: float = math.sqrt(s) if s > 1e-12 else 1e-6
        rs: float = r / std
        # Raw log-ratio against window span -> clamp to [0,1].
        h: float = math.log(max(rs, 1e-9)) / math.log(max(len(vals), 2))
        self.hurst_index = max(0.0, min(1.0, h))
        # Free transient.
        del vals, mean_r, cumdev, s, std

    def _update_liquidity(self, tick: Dict[str, Any]) -> None:
        """Update liquidity scale + imbalance from top-of-book depth if present."""
        bid_depth: float = float(tick.get("bid_depth", 0.0) or 0.0)
        ask_depth: float = float(tick.get("ask_depth", 0.0) or 0.0)
        depth: float = bid_depth + ask_depth
        if depth > 0:
            self.depth_series.push(depth)
            mean_d: float = self.depth_series.mean
            if mean_d > 0:
                raw: float = depth / mean_d
                lo: float = float(self.cfg["min_depth_scale"])
                hi: float = float(self.cfg["max_depth_scale"])
                self.liquidity_scale = max(lo, min(hi, raw))
            denom: float = bid_depth + ask_depth
            if denom > 0:
                self.imbalance = (bid_depth - ask_depth) / denom
        else:
            self.liquidity_scale = 1.0
            self.imbalance = 0.0

    def _vol_target_position(self) -> float:
        """Volatility-targeted notional position (in quote units)."""
        atr: float = self.atr_ewma.mean
        price: float = self.price
        if price <= 0.0 or atr <= 0.0:
            return 0.0
        vol: float = atr / price
        if vol <= 1e-9:
            return 0.0
        target_notional: float = float(self.cfg["vol_target"]) / vol
        capital: float = float(self.cfg["capital"])
        return max(0.0, min(capital, target_notional))

    # ---- interface ------------------------------------------------------- #
    def on_tick(self, tick: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Process one market tick. Returns an order intent dict or None."""
        price: float = float(tick.get("price", 0.0) or 0.0)
        if price <= 0.0:
            return None
        self.last_price = self.price
        self.price = price

        # Vol estimator: |log-return|.
        if self.last_price and self.last_price > 0.0:
            ret: float = math.log(price / self.last_price)
            self.atr_ewma.push(abs(ret) * float(self.cfg["atr_k"]))
            self.returns.append(ret)

        self._update_liquidity(tick)
        self._update_hurst()

        regime: str = "meanrev"
        if self.hurst_index > float(self.cfg["hurst_high"]):
            regime = "trend"
        elif self.hurst_index < float(self.cfg["hurst_low"]):
            regime = "squeeze"

        # Core price anchor with imbalance-damped recentre.
        anchor: float = price
        shift: float = self.imbalance * float(self.cfg["max_imbalance_shift"])
        anchor *= 1.0 + shift

        atr: float = self.atr_ewma.mean
        spacing: float = atr * self.liquidity_scale
        if spacing <= 0.0:
            spacing = price * 0.001

        # Order intent (simple: long if below mean-reversion band, short if above).
        band: float = spacing * 1.5
        side: str = ""
        if regime == "meanrev":
            side = "buy" if price < anchor - band else ("sell" if price > anchor + band else "")
        elif regime == "squeeze":
            # Tighter bands when vol is squeezing.
            side = "buy" if price < anchor - band * 0.6 else (
                "sell" if price > anchor + band * 0.6 else ""
            )
        elif regime == "trend":
            # Breakout overlay: only trade the break of the outer band with momentum.
            side = "buy" if price > anchor + band * 3.0 else ""

        if not side or self.trade_count >= int(self.cfg["max_trades"]):
            return None

        qty: float = self._vol_target_position() / price
        cap: float = qty * price
        # Liquidity cap: never post more than a fraction of observed depth.
        bid_depth: float = float(tick.get("bid_depth", 0.0) or 0.0)
        if side == "buy" and bid_depth > 0:
            max_qty: float = bid_depth * float(self.cfg["max_liquidity_fill_pct"])
            qty = min(qty, max_qty)

        self.trade_count += 1
        oid: str = f"lsmr_{self.trade_count}_{self._n(price)}"
        self.orders[oid] = {
            "side": side,
            "price": price,
            "qty": qty,
            "regime": regime,
            "spacing": spacing,
        }
        return {
            "order_id": oid,
            "side": side,
            "price": price,
            "qty": qty,
            "notional": cap,
            "regime": regime,
        }

    @staticmethod
    def _n(x: Any) -> int:
        return abs(hash((type(x).__name__, str(x)))) % 10**6

    def on_fill(self, fill: Dict[str, Any]) -> None:
        """Handle a fill: update position and realized PnL."""
        oid: str = str(fill.get("order_id", ""))
        side: str = str(fill.get("side", "buy")).lower()
        price: float = float(fill.get("price", 0.0) or 0.0)
        qty: float = float(fill.get("qty", 0.0) or 0.0)
        if oid in self.orders:
            del self.orders[oid]
            gc.collect()
        sign: float = 1.0 if side in ("buy", "b") else -1.0
        old_pos: float = self.position
        self.position += sign * qty
        if price > 0.0 and qty > 0.0:
            if old_pos == 0.0:
                self.entry_price = price
            elif (old_pos > 0 and sign < 0) or (old_pos < 0 and sign > 0):
                # Closing side: lock PnL.
                close_qty: float = min(abs(qty), abs(old_pos))
                if self.entry_price is not None:
                    if old_pos > 0:
                        self.realized_pnl += close_qty * (price - self.entry_price)
                    else:
                        self.realized_pnl += close_qty * (self.entry_price - price)
                if abs(self.position) < 1e-12:
                    self.position = 0.0
                    self.entry_price = None


# --------------------------------------------------------------------------- #
# Inline synthetic smoke test (small dataset, no external deps).
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    import random

    random.seed(42)
    cfg: Dict[str, Any] = {"capital": 100.0, "max_trades": 12}
    s = LSMR_ARX(cfg)
    print(f"mem_estimate_mb={s.estimate_memory_mb()}")
    fills: int = 0
    price: float = 100.0
    for i in range(2000):
        price *= 1.0 + random.gauss(0, 0.003)
        tick: Dict[str, Any] = {
            "price": price,
            "bid_depth": 50 + (i % 10) * 3,
            "ask_depth": 48 + (i % 9) * 4,
        }
        order = s.on_tick(tick)
        if order:
            s.on_fill(
                {
                    "order_id": order["order_id"],
                    "side": order["side"],
                    "price": price,
                    "qty": order["qty"],
                }
            )
            fills += 1
    print(f"orders_filled={fills} position={s.position:.4f} pnl={s.realized_pnl:.4f}")
    assert s.estimate_memory_mb() < 1.0, "memory estimate out of bounds"
    print("SMOKE TEST PASS")
