"""Quote-Reserve Standby Grid (QRSG)
Auto-generated by Hermes orchestrator.

Problem this solves: during exchange-side capital droughts (OKX 51008
EUR insufficient), grid bots hammer repeated failed buy orders at ~4/min,
locking quote balance that never fills on the book. Classic grid keeps
placing orders unconditionally and wastes cycles + risks cascade failures.

Novel corner vs FRWG-CRA: instead of widening spacing under rejection,
QRSG reserves a hard floor of free quote and STANDS DOWN the entire BUY
side while retained quote is at or below the reserve. It only resumes the
buy ladder after the reserve is rebuilt (via a sell fill or external top-up),
so the bot never presses a dry book. Sell side keeps running to harvest
profits and rebuild the reserve. Fully config-driven.

OOM-safe: O(1) streaming state, no data materialization, no 100k+ loops.
"""

from __future__ import annotations

import gc
import logging
from typing import Any, Dict, Optional

log = logging.getLogger("denaro.strategy.qrsg")


class StrategyBase:
    """Interface contract all Denaro strategies implement."""

    def __init__(self, config: Dict[str, Any]) -> None:
        self.config = config
        self.validate_config(config)

    # -- required hooks (subclass overrides) --------------------------------
    def on_tick(self, engine_state: Dict[str, Any]) -> Dict[str, Any]:
        raise NotImplementedError

    def on_fill(self, fill: Dict[str, Any]) -> None:
        raise NotImplementedError

    # -- shared helpers -------------------------------------------------------
    def validate_config(self, config: Dict[str, Any]) -> None:
        required = {
            "symbol": str,
            "capital": (int, float),
            "levels": int,
            "spacing": (int, float),
        }
        missing = [k for k, t in required.items() if not isinstance(config.get(k), t)]
        if missing:
            raise ValueError(f"QRSG config missing/wrong-typed keys: {missing}")
        if config["levels"] < 1:
            raise ValueError("QRSG levels must be >= 1")
        if config["spacing"] <= 0:
            raise ValueError("QRSG spacing must be > 0")

    def estimate_memory_mb(self) -> float:
        # ~200B state object + config, constant regardless of levels
        return 0.02


class QRSG(StrategyBase):
    """Quote-Reserve Standby Grid with buy-side stand-down.

    Config keys:
      symbol       : trading pair (e.g. DOGE/EUR)
      capital      : total quote capital allocated
      levels       : number of grid levels per side
      spacing      : relative grid spacing (e.g. 0.015 = 1.5%)
      reserve_frac : fraction of capital kept as hard reserve (default 0.35)
      fee          : taker fee fraction for loss estimation (default 0.002)
      recovery_frac: quote fraction that must be >= reserve to re-arm buys
    """

    def __init__(self, config: Dict[str, Any]) -> None:
        super().__init__(config)
        self.reserve_frac: float = float(config.get("reserve_frac", 0.35))
        self.fee: float = float(config.get("fee", 0.002))
        self.recovery_frac: float = float(config.get("recovery_frac", 1.10))
        self._active_orders: int = 0
        self._buy_stand_down: bool = False
        self._reserve_open: bool = False
        self._reserve_floor: float = float(config["capital"]) * self.reserve_frac

    def _should_stand_down(self, free_quote: float) -> bool:
        """True when free quote (available for buys) is at/below reserve floor."""
        if free_quote <= self._reserve_floor:
            self._reserve_open = True
            return True
        # hysteresis: re-arm only once reserve rebuilt past recovery threshold
        if self._reserve_open and free_quote < self._reserve_floor * self.recovery_frac:
            return True
        self._reserve_open = False
        return False

    def on_tick(self, engine_state: Dict[str, Any]) -> Dict[str, Any]:
        price: float = float(engine_state.get("price") or 0.0)
        free_quote: float = float(engine_state.get("free_quote") or 0.0)
        if price <= 0.0:
            log.debug("QRSG: no valid price, no signal")
            return {"action": "hold", "reason": "no_price"}

        stand_down = self._should_stand_down(free_quote)
        self._buy_stand_down = stand_down

        buy_levels: int = 0 if stand_down else int(self.config["levels"])
        # cluster size sized against reserve protection: never exceed what
        # a single adverse wick could cost minus fee headroom
        max_loss = free_quote * 0.01 + self.fee * self.config["capital"]
        protective = max(1, int(self._reserve_floor / max(self.config["spacing"], 1e-9)))
        buy_levels = min(buy_levels, protective)

        note = "buy_stand_down_reserve_floor" if stand_down else "buy_ladder_active"
        log.info(
            "QRSG tick price=%.6f free=%.4f reserve=%.4f stand_down=%s levels=%d state=%s",
            price, free_quote, self._reserve_floor, stand_down, buy_levels, note,
        )
        return {
            "action": "rebalance",
            "buy_levels": buy_levels,
            "sell_levels": int(self.config["levels"]),
            "spacing": float(self.config["spacing"]),
            "state": note,
            "reserve_floor": self._reserve_floor,
            "free_quote": free_quote,
        }

    def on_fill(self, fill: Dict[str, Any]) -> None:
        side: str = str(fill.get("side", "")).lower()
        if side == "sell":
            # a sell rebuilds quote -> refresh reserve floor and possibly re-arm
            collected: float = float(fill.get("value") or 0.0)
            self._reserve_open = collected <= 0.0  # unknown fill -> keep door open
            log.info("QRSG sell fill value=%.4f recheck reserve", collected)
        self._active_orders = max(0, self._active_orders + (1 if side == "buy" else -1))


if __name__ == "__main__":
    # inline self-test with small synthetic data

    def _run() -> None:
        s = QRSG({
            "symbol": "DOGE/EUR", "capital": 3.7, "levels": 8,
            "spacing": 0.015, "reserve_frac": 0.35, "fee": 0.002,
        })
        assert s.estimate_memory_mb() < 1.0, "memory estimate must be tiny"
        # free quote above reserve -> ladder active
        r1 = s.on_tick({"price": 0.11, "free_quote": 2.75})
        assert r1["state"] == "buy_ladder_active", r1
        assert r1["buy_levels"] > 0, r1
        # drop free quote below reserve floor -> stand down buys
        r2 = s.on_tick({"price": 0.11, "free_quote": 0.80})
        assert r2["state"] == "buy_stand_down_reserve_floor", r2
        assert r2["buy_levels"] == 0, r2
        # sell fill rebuilds reserve -> re-arm
        s.on_fill({"side": "sell", "value": 2.0})
        r3 = s.on_tick({"price": 0.11, "free_quote": 2.00})
        assert r3["state"] == "buy_ladder_active", r3
        del r1, r2, r3
        gc.collect()
        print("QRSG self-test PASSED")

    _run()
