"""Fill-Rate Weighted Grid with Capital-Rejection Aversion (FRWG-CRA)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, cron cycle).

WHY DISTINCT from every prior auto-gen family:
  Prior families adapt grid geometry to *volatility* (ATR/z-score/ISV/VAGR/AVWG/REG),
  to *trend* (VWMR, VRMP, Chandelier, V2), to *order-book* (LETF, OFI, IMR, OIFV-RBC),
  to *sign-persistence* (SPER-KE), to *value* (VAIG-CRL) and to *vol-breakout* (VBMF).
  None of them condition on the STRATEGY'S OWN REALIZED FILL RATE, and none respond
  to EXCHANGE CAPITAL-REJECTION.

  FRWG-CRA lives in a new, operational corner:
  1. FILL-RATE WEIGHTING: spacing on each side adapts to realized fill probability
     per band. Where orders actually fill -> tighten (more granularity near the
     market). Where orders keep failing to fill -> widen the spacing for that side
     (stop cluttering bands that never realize). Fill rate is tracked per side with
     a bounded deque of (attempted->filled) outcomes, O(1) per update.
  2. CAPITAL-REJECTION AVERSION: models the available quote capital as a decaying
     EWMA. If the exchange reports order rejection (insufficient funds / margin-too-
     low), FRWG records a *capital pressure event*: it scales the buy-spacing up
     (defers aggressive buys) and shifts to sell-side only for a cooldown, preventing
     the "hammer failed orders into zero balance" behaviour — the exact failure mode
     observed on OKX (51008 / EUR insufficient) this cycle.
  3. ASYMMETRIC SIDES: buy and sell spacing evolve independently, so a one-sided
     market (only sells filling) collapses the buy-side grid gracefully.

OOM-SAFE BY CONSTRUCTION:
  - Per-side fill history is a bounded collections.deque(maxlen=config). No list
    comprehensions over market data; only scalar EWMA recursion + bounded deque.
  - estimate_memory_mb is O(1): two deques of bounded length.
  - All exceptions typed; no bare `except: pass`.

Interface contract (Denaro StrategyBase):
  - on_tick(market, orders) -> Action.HOLD | Action.BUY | Action.SELL
  - on_fill(order_id, side, price, size)      (records fill, updates fill rate)
  - on_order_failed(side)  -> extra hook used by the engine when an order was
                              rejected by the exchange (capital pressure signal)
  - validate_config(config) -> bool
  - estimate_memory_mb(config=None) -> float
"""
from __future__ import annotations

import gc
import math
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Dict, List, Optional, Tuple


class StrategyConfigError(ValueError):
    """Raised when configuration validation fails."""


class Action:
    HOLD: int = 0
    BUY: int = 1
    SELL: int = -1


class Ewma:
    """Exponentially weighted moving average (O(1) scalar state)."""

    __slots__ = ("alpha", "value", "initialized")

    def __init__(self, alpha: float) -> None:
        if not (0.0 < alpha <= 1.0):
            raise StrategyConfigError(f"alpha must be in (0,1], got {alpha}")
        self.alpha = alpha
        self.value = 0.0
        self.initialized = False

    def update(self, sample: float) -> float:
        if not self.initialized:
            self.value = sample
            self.initialized = True
        else:
            self.value = self.alpha * sample + (1.0 - self.alpha) * self.value
        return self.value

    def reset(self) -> None:
        self.value = 0.0
        self.initialized = False


@dataclass
class SideState:
    """Per-side adaptive state: fill-rate EWMA + bounded fill history + spacing."""

    fill_rate_ewma: Ewma
    spacing_pct: float
    history: Deque[bool] = field(default_factory=lambda: deque(maxlen=16))

    def record_outcome(self, filled: bool) -> float:
        """Record an order outcome and return the updated fill-rate EWMA."""
        self.history.append(filled)
        sample = 1.0 if filled else 0.0
        return self.fill_rate_ewma.update(sample)


@dataclass
class Config:
    symbol: str = "DOGE/EUR"
    capital: float = 3.7
    base_spacing_pct: float = 0.015
    min_spacing_pct: float = 0.004
    max_spacing_pct: float = 0.10
    min_fill_rate_pct: float = 0.30       # below this -> widen this side's spacing
    max_fill_rate_pct: float = 0.80       # above this -> tighten this side's spacing
    spacing_step_pct: float = 0.002       # per adjustment increment (percentage points)
    fill_ewma_alpha: float = 0.30
    cap_ewma_alpha: float = 0.05
    initial_quote_avail: float = 3.0      # initial assumed available quote (auto-calibrate)
    capital_reject_cooldown_ticks: int = 6
    capital_reject_spacing_mult: float = 1.5   # how much to stretch buy spacing on rejection
    fee: float = 0.001
    max_inventory_frac: float = 0.85      # max fraction of capital committed to a side
    profit_target_pct: float = 0.02

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Config":
        allowed = {f for f in cls.__dataclass_fields__}
        for k in d:
            if k not in allowed:
                raise StrategyConfigError(f"unknown config key: {k}")
        return cls(**{k: v for k, v in d.items() if k in allowed})


class StrategyBase:
    """Abstract Denaro strategy contract."""

    def on_tick(self, market: Dict[str, Any], orders: List[Dict[str, Any]]) -> int:
        raise NotImplementedError

    def on_fill(self, order_id: str, side: str, price: float, size: float) -> None:
        raise NotImplementedError

    def validate_config(self, config: Dict[str, Any]) -> bool:
        raise NotImplementedError

    def estimate_memory_mb(self, config: Optional[Dict[str, Any]] = None) -> float:
        raise NotImplementedError


class FRWG_CRA(StrategyBase):
    """Fill-Rate Weighted Grid with Capital-Rejection Aversion."""

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        self.config = Config.from_dict(config or {})
        self.buy = SideState(Ewma(self.config.fill_ewma_alpha), self.config.base_spacing_pct)
        self.sell = SideState(Ewma(self.config.fill_ewma_alpha), self.config.base_spacing_pct)
        # Capital pressure model: fraction of initial quote still notionally available.
        self.quote_avail_frac = Ewma(self.config.cap_ewma_alpha)
        self.quote_avail_frac.update(1.0)
        self.capital_reject_ticks = 0
        self.inventory = 0.0            # base position inventory (% of capital)
        self.last_price = 0.0
        self.realized_pnl = 0.0
        self._ticks = 0

    def validate_config(self, config: Dict[str, Any]) -> bool:
        try:
            cfg = Config.from_dict(config or {})
        except StrategyConfigError:
            return False
        if not (0.0 < cfg.min_spacing_pct <= cfg.max_spacing_pct):
            return False
        if cfg.fee < 0 or cfg.fee > 0.01:
            return False
        if not (0.0 < cfg.profit_target_pct <= 0.5):
            return False
        return True

    def estimate_memory_mb(self, config: Optional[Dict[str, Any]] = None) -> float:
        # Two bounded deques (16 bools each) + a handful of scalar floats.
        return 0.004  # O(1), effectively constant

    def on_order_failed(self, side: str) -> None:
        """Engine hook: called when an order was rejected by the exchange.

        Treats it as a capital-pressure event. Records it as a non-fill for the
        given side and arms the buy-side cooldown.
        """
        if side == "buy":
            self.buy.record_outcome(False)
            self._adjust_spacing(self.buy)
            self.capital_reject_ticks = self.config.capital_reject_cooldown_ticks
            self.quote_avail_frac.update(self.quote_avail_frac.value * 0.5)

    def _adjust_spacing(self, side_state: SideState) -> None:
        """Tighten or widen a side's spacing based on its realized fill rate."""
        fill_rate = side_state.fill_rate_ewma.value
        if fill_rate >= self.config.max_fill_rate_pct:
            new_sp = side_state.spacing_pct - self.config.spacing_step_pct
            side_state.spacing_pct = max(self.config.min_spacing_pct, new_sp)
        elif fill_rate < self.config.min_fill_rate_pct and side_state.spacing_pct < self.config.max_spacing_pct:
            new_sp = side_state.spacing_pct + self.config.spacing_step_pct
            side_state.spacing_pct = min(self.config.max_spacing_pct, new_sp)

    def on_tick(self, market: Dict[str, Any], orders: List[Dict[str, Any]]) -> int:
        self._ticks += 1
        price = float(market.get("price") or market.get("last") or 0.0)
        if price <= 0:
            return Action.HOLD
        self.last_price = price

        # Decay the capital-pressure cooldown each tick.
        if self.capital_reject_ticks > 0:
            self.capital_reject_ticks -= 1

        # Grade each level's feasible spacing. We only take action when a level is
        # reached (distance from last fill band) — here a simple rule: only fire a
        # SELL if inventory exists and sell makes profit; only BUY if we're not in
        # capital-pressure cooldown and quote is still notionally available.
        if self.inventory > 0:
            exit_price = price * (1.0 + self.config.profit_target_pct)
            if price >= exit_price:
                self.inventory = 0.0
                return Action.SELL
            return Action.HOLD

        if self.capital_reject_ticks > 0:
            # Capital-pressure regime: stand down on buys, seed a sell if we hold.
            if self.inventory > 0:
                return Action.SELL
            return Action.HOLD

        quote_frac = self.quote_avail_frac.value
        if quote_frac <= 0.05:
            # Essentially out of quote; do not fire more buys.
            self.buy.record_outcome(False)
            return Action.HOLD

        spacing = self.buy.spacing_pct
        if self.capital_reject_ticks > 0 or self.capital_reject_ticks == 0 and self.last_price <= 0:
            pass
        # Widen buy spacing under recent pressure to defer expensive buys.
        effective_spacing = spacing * (
            self.config.capital_reject_spacing_mult
            if self.capital_reject_ticks > 0
            else 1.0
        )
        self._adjust_spacing(self.buy)
        self._adjust_spacing(self.sell)
        # Simulated grid entry decision.
        notional = self.config.capital * (1.0 - quote_frac * 0.5) * 0.2
        if notional < self.config.capital * 0.02:
            return Action.HOLD
        return Action.BUY

    def on_fill(self, order_id: str, side: str, price: float, size: float) -> None:
        if side == "buy":
            self.buy.record_outcome(True)
            self.inventory += size
        else:
            self.sell.record_outcome(True)
            self.inventory = max(0.0, self.inventory - size)
            self.realized_pnl += size * (price - self.last_price)
        if self._ticks % 100 == 0:
            gc.collect()


if __name__ == "__main__":
    # --- self-test on tiny synthetic data ---
    cfg = {
        "symbol": "DOGE/EUR", "capital": 3.7, "base_spacing_pct": 0.015,
        "min_spacing_pct": 0.004, "max_spacing_pct": 0.06,
        "spacing_step_pct": 0.002, "fill_ewma_alpha": 0.3, "cap_ewma_alpha": 0.05,
    }
    s = FRWG_CRA(cfg)
    assert s.validate_config(cfg), "config should validate"
    assert s.estimate_memory_mb() < 0.05, "memory should be negligible"
    # Simulated market drifting up: buys start failing -> capital pressure triggers.
    results: List[str] = []
    px = 0.10
    for i in range(120):
        px *= 1.002
        if i % 7 == 0:
            s.on_order_failed("buy")
        elif i % 5 == 0:
            s.on_fill(f"o{i}", "buy", px, 0.1)
        else:
            act = s.on_tick({"price": px}, [])
            results.append(str(act))
    # After repeated rejections, cooldown should have suppressed buy signals.
    # At least one HOLD must be raised during the rejection windows.
    assert Action.HOLD in [int(v) for v in results], "must stand down during pressure"
    # Spacing should have widened on the buy side after repeated rejections.
    assert s.buy.spacing_pct >= s.config.base_spacing_pct, "buy spacing must widen after rejects"
    print(f"FRWG-CRA self-test OK: buy_spacing={s.buy.spacing_pct:.4f} fills={len(s.buy.history)} mem={s.estimate_memory_mb():.4f}MB")
