"""
Adaptive Grid-Momentum Hybrid Strategy
Generated by Hermes Strategy Engineer v1
Timestamp: 2026-08-28 11:50:54 UTC

Combines grid trading with momentum filtering:
- Grid places buy/sell orders around fair value
- Momentum filter pauses grid when trend is strong
- Dynamic spacing based on ATR volatility
- Capital-efficient: reuses filled orders as new grid levels
"""

from __future__ import annotations

import gc
import math
from dataclasses import dataclass, field
from typing import Generator, Iterator, Optional
from collections import deque


@dataclass(frozen=True, slots=True)
class StrategyConfig:
    """Configuration for AdaptiveGridMomentum strategy."""
    symbol: str
    base_capital: float
    grid_levels: int = 10
    base_spacing_pct: float = 0.008  # 0.8% base spacing
    atr_period: int = 14
    atr_multiplier: float = 1.5
    momentum_lookback: int = 20
    momentum_threshold: float = 0.015  # 1.5% momentum to pause grid
    max_position_pct: float = 0.8  # max 80% of capital in position
    min_order_size: float = 10.0  # minimum order size in quote currency
    fee_rate: float = 0.0016  # maker fee (Kraken default)
    enable_momentum_filter: bool = True
    rebalance_interval_sec: int = 300  # 5 min rebalance check

    def validate(self) -> None:
        if self.base_capital <= 0:
            raise ValueError("base_capital must be positive")
        if self.grid_levels < 2:
            raise ValueError("grid_levels must be >= 2")
        if not 0 < self.base_spacing_pct < 0.1:
            raise ValueError("base_spacing_pct must be in (0, 0.1)")
        if self.atr_period < 2:
            raise ValueError("atr_period must be >= 2")
        if self.momentum_lookback < 5:
            raise ValueError("momentum_lookback must be >= 5")
        if not 0 < self.max_position_pct <= 1:
            raise ValueError("max_position_pct must be in (0, 1]")


@dataclass(slots=True)
class GridLevel:
    """Single grid level with order tracking."""
    price: float
    side: str  # 'buy' or 'sell'
    order_id: Optional[str] = None
    filled: bool = False
    filled_qty: float = 0.0
    filled_price: float = 0.0


@dataclass(slots=True)
class MarketState:
    """Rolling market state for streaming calculation."""
    prices: deque = field(default_factory=lambda: deque(maxlen=200))
    highs: deque = field(default_factory=lambda: deque(maxlen=200))
    lows: deque = field(default_factory=lambda: deque(maxlen=200))
    volumes: deque = field(default_factory=lambda: deque(maxlen=200))
    atr: float = 0.0
    momentum: float = 0.0
    fair_value: float = 0.0

    def update(self, price: float, high: float, low: float, volume: float) -> None:
        self.prices.append(price)
        self.highs.append(high)
        self.lows.append(low)
        self.volumes.append(volume)
        self._recalc()

    def _recalc(self) -> None:
        if len(self.prices) < 2:
            return
        # ATR calculation (streaming)
        if len(self.highs) >= self.atr_period + 1:
            tr_sum = 0.0
            for i in range(-self.atr_period, 0):
                tr = max(
                    self.highs[i] - self.lows[i],
                    abs(self.highs[i] - self.prices[i - 1]),
                    abs(self.lows[i] - self.prices[i - 1])
                )
                tr_sum += tr
            self.atr = tr_sum / self.atr_period
        # Momentum: (price_now / price_lookback_ago) - 1
        if len(self.prices) >= self.momentum_lookback:
            self.momentum = (self.prices[-1] / self.prices[-self.momentum_lookback]) - 1
        # Fair value: VWAP over recent window
        vwap_window = min(50, len(self.prices))
        pv_sum = sum(self.prices[-i] * self.volumes[-i] for i in range(1, vwap_window + 1))
        vol_sum = sum(self.volumes[-i] for i in range(1, vwap_window + 1))
        self.fair_value = pv_sum / vol_sum if vol_sum > 0 else self.prices[-1]

    # These will be set by strategy instance
    atr_period: int = 14
    momentum_lookback: int = 20


class StrategyBase:
    """Base class for all strategies."""
    def __init__(self, config: StrategyConfig) -> None:
        self.config = config
        config.validate()
        self.state = MarketState()
        self.state.atr_period = config.atr_period
        self.state.momentum_lookback = config.momentum_lookback
        self.grid: list[GridLevel] = []
        self.position: float = 0.0  # base currency position
        self.realized_pnl: float = 0.0
        self.unrealized_pnl: float = 0.0
        self.total_fees: float = 0.0
        self._last_rebalance: float = 0.0

    def on_tick(
        self,
        timestamp: float,
        price: float,
        high: float,
        low: float,
        volume: float,
        free_quote: float,
        free_base: float
    ) -> list[dict]:
        """Process market tick, return list of order actions."""
        raise NotImplementedError

    def on_fill(self, order_id: str, side: str, price: float, qty: float, fee: float) -> None:
        """Handle order fill."""
        raise NotImplementedError

    def validate_config(self) -> bool:
        try:
            self.config.validate()
            return True
        except ValueError:
            return False

    def estimate_memory_mb(self) -> float:
        """Estimate memory usage in MB."""
        # deques: 4 * 200 * 8 bytes = ~6.4 KB
        # grid: 10 * ~200 bytes = ~2 KB
        # overhead: ~1 MB
        return 1.5


class AdaptiveGridMomentum(StrategyBase):
    """
    Adaptive Grid with Momentum Filter.
    
    Features:
    - Dynamic grid spacing based on ATR
    - Momentum filter pauses new grid orders during strong trends
    - Capital recycling: filled orders become new opposite-side levels
    - Streaming calculation - O(1) memory per tick
    """

    def __init__(self, config: StrategyConfig) -> None:
        super().__init__(config)
        self._grid_initialized: bool = False

    def _init_grid(self, fair_value: float, spacing: float) -> None:
        """Initialize grid levels around fair value."""
        self.grid.clear()
        half = self.config.grid_levels // 2
        for i in range(-half, half + 1):
            if i == 0:
                continue
            level_price = fair_value * (1 + i * spacing)
            side = 'buy' if i < 0 else 'sell'
            self.grid.append(GridLevel(price=level_price, side=side))
        self._grid_initialized = True

    def _calculate_dynamic_spacing(self) -> float:
        """Calculate grid spacing based on ATR."""
        if self.state.atr <= 0 or self.state.fair_value <= 0:
            return self.config.base_spacing_pct
        atr_pct = self.state.atr / self.state.fair_value
        # Scale base spacing by ATR, clamp to reasonable bounds
        dynamic = self.config.base_spacing_pct * max(0.5, min(3.0, atr_pct / 0.02))
        return max(0.003, min(0.03, dynamic))  # 0.3% - 3% bounds

    def _should_pause_grid(self) -> bool:
        """Check if momentum filter should pause grid."""
        if not self.config.enable_momentum_filter:
            return False
        return abs(self.state.momentum) > self.config.momentum_threshold

    def _generate_orders(
        self,
        price: float,
        free_quote: float,
        free_base: float
    ) -> list[dict]:
        """Generate order actions for current grid state."""
        orders = []
        spacing = self._calculate_dynamic_spacing()
        
        if not self._grid_initialized:
            self._init_grid(self.state.fair_value, spacing)
            return orders

        # Check if we need to rebalance grid (fair value shifted)
        current_center = (self.grid[0].price + self.grid[-1].price) / 2
        if abs(current_center - self.state.fair_value) / self.state.fair_value > spacing * 0.5:
            # Re-center grid
            self._init_grid(self.state.fair_value, spacing)
            return orders

        # Place/move orders for unfilled levels
        max_position_value = self.config.base_capital * self.config.max_position_pct
        current_position_value = abs(self.position) * price
        
        for level in self.grid:
            if level.filled or level.order_id is not None:
                continue
            
            # Check capital constraints
            if level.side == 'buy':
                required_quote = level.price * self.config.min_order_size / price
                if required_quote > free_quote * 0.9:  # keep 10% buffer
                    continue
                if current_position_value + required_quote > max_position_value:
                    continue
            else:  # sell
                required_base = self.config.min_order_size / price
                if required_base > free_base * 0.9:
                    continue
            
            # Momentum filter: pause new orders against trend
            if self._should_pause_grid():
                if (level.side == 'buy' and self.state.momentum < 0) or \
                   (level.side == 'sell' and self.state.momentum > 0):
                    continue
            
            orders.append({
                'symbol': self.config.symbol,
                'side': level.side,
                'price': round(level.price, 5),
                'amount': round(self.config.min_order_size / level.price, 6),
                'type': 'limit',
                'post_only': True,
                'meta': {'grid_level': True, 'spacing_pct': spacing}
            })
        
        return orders

    def on_tick(
        self,
        timestamp: float,
        price: float,
        high: float,
        low: float,
        volume: float,
        free_quote: float,
        free_base: float
    ) -> list[dict]:
        """Process market tick - streaming, O(1) memory."""
        self.state.update(price, high, low, volume)
        
        # Periodic garbage collection for long-running processes
        if int(timestamp) % 3600 == 0:
            gc.collect()
        
        return self._generate_orders(price, free_quote, free_base)

    def on_fill(self, order_id: str, side: str, price: float, qty: float, fee: float) -> None:
        """Handle fill: update position, recycle grid level."""
        self.total_fees += fee
        
        # Find and update grid level
        for level in self.grid:
            if level.order_id == order_id:
                level.filled = True
                level.filled_qty = qty
                level.filled_price = price
                break
        
        # Update position
        if side == 'buy':
            self.position += qty
            self.realized_pnl -= fee
        else:
            self.position -= qty
            self.realized_pnl -= fee
        
        # Recycle: create new opposite level at filled price * (1 ± spacing)
        spacing = self._calculate_dynamic_spacing()
        if side == 'buy':
            # Filled buy -> place sell above
            new_price = price * (1 + spacing)
            new_side = 'sell'
        else:
            # Filled sell -> place buy below
            new_price = price * (1 - spacing)
            new_side = 'buy'
        
        # Replace filled level with new recycled level
        for i, level in enumerate(self.grid):
            if level.order_id == order_id:
                self.grid[i] = GridLevel(price=new_price, side=new_side)
                break
        
        # Update unrealized PnL
        self.unrealized_pnl = self.position * (price - self.state.fair_value)


def generate_synthetic_data(
    n: int = 1000,
    start_price: float = 100.0,
    volatility: float = 0.02,
    trend: float = 0.0001
) -> Generator[tuple[float, float, float, float, float], None, None]:
    """Generate synthetic OHLCV data for testing. Memory efficient generator."""
    import random
    price = start_price
    for i in range(n):
        # Random walk with drift
        change = random.gauss(trend, volatility)
        price *= (1 + change)
        
        # Generate OHLC from price
        high = price * (1 + abs(random.gauss(0, volatility * 0.5)))
        low = price * (1 - abs(random.gauss(0, volatility * 0.5)))
        volume = random.uniform(100, 10000)
        
        yield (float(i), price, high, low, volume)
    
    # Explicit cleanup
    del price, change, high, low, volume
    gc.collect()


if __name__ == "__main__":
    # Inline test with synthetic data
    print("Testing AdaptiveGridMomentum strategy...")
    
    config = StrategyConfig(
        symbol="SOL/EUR",
        base_capital=100.0,
        grid_levels=10,
        base_spacing_pct=0.008,
        atr_period=14,
        atr_multiplier=1.5,
        momentum_lookback=20,
        momentum_threshold=0.015,
        max_position_pct=0.8,
        min_order_size=10.0,
        fee_rate=0.0016
    )
    
    strategy = AdaptiveGridMomentum(config)
    print(f"Config valid: {strategy.validate_config()}")
    print(f"Estimated memory: {strategy.estimate_memory_mb():.2f} MB")
    
    # Simulate ticks
    free_quote = 100.0
    free_base = 0.0
    orders_placed = 0
    fills_simulated = 0
    
    for tick_data in generate_synthetic_data(n=500, start_price=150.0, volatility=0.015):
        ts, price, high, low, vol = tick_data
        orders = strategy.on_tick(ts, price, high, low, vol, free_quote, free_base)
        
        if orders:
            orders_placed += len(orders)
            # Simulate fills for first few orders
            if fills_simulated < 3:
                for order in orders[:1]:
                    strategy.on_fill(
                        order_id=f"test_{fills_simulated}",
                        side=order['side'],
                        price=order['price'],
                        qty=order['amount'],
                        fee=order['price'] * order['amount'] * config.fee_rate
                    )
                    fills_simulated += 1
                    free_quote -= order['price'] * order['amount'] if order['side'] == 'buy' else 0
                    free_base += order['amount'] if order['side'] == 'buy' else 0
    
    print(f"Orders placed: {orders_placed}")
    print(f"Fills simulated: {fills_simulated}")
    print(f"Final position: {strategy.position:.6f}")
    print(f"Realized PnL: {strategy.realized_pnl:.4f}")
    print(f"Unrealized PnL: {strategy.unrealized_pnl:.4f}")
    print(f"Total fees: {strategy.total_fees:.4f}")
    print(f"Grid levels: {len(strategy.grid)}")
    print("Test completed successfully.")
