"""
Vol-Target Kelly Grid with Drawdown-Asymmetric Re-entry (VTK-GAR)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1).
Cycle 2026-08-29 20:04 UTC.

Improvement vs RPVL-EGR (auto_gen_1788025859): continuous vol-targeting
position sizing scales capital by 1/vol (asymmetric), plus drawdown-gated
re-entry with cooling reacting to realised losses. OOM-safe: O(1) per tick,
no history retention beyond EWMA scalars.
"""
from __future__ import annotations
import gc
import math
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Dict, List, Optional, Tuple

DEFAULT_CONFIG: Dict[str, Any] = {
    "symbol": "SOL/EUR",
    "capital": 13.5,
    "vol_ewma_span": 24,
    "target_vol": 0.012,
    "min_vol_floor": 0.004,
    "max_vol_ceil": 0.050,
    "vol_scale_power": 1.0,
    "base_spacing_pct": 0.010,
    "max_levels": 9,
    "fee": 0.0016,
    "kelly_fraction": 0.30,
    "win_prob_assumed": 0.55,
    "dd_gate": 0.06,
    "dd_reentry_cool": 4,
    "stop_loss_frac": 0.12,
    "pending_cap": 20,   # memory-safety hard cap on live grid levels
}
OPTIONAL_KEYS: Tuple[str, ...] = ()
MAX_PENDING_LEVELS = 20  # hard cap per sicurezza memoria


@dataclass
class EngineState:
    free_quote: float = 0.0
    total_equity: float = 0.0
    last_price: Optional[float] = None
    halt: bool = False
    regime: str = "neutral"
    levels: int = 0
    spacing: float = 0.0
    pending: Deque[float] = field(default_factory=deque)
    position_fills: int = 0
    realised_pnl: float = 0.0
    vol_ewma: float = 0.0
    ewm_count: int = 0
    equity_hwm: float = 0.0
    dd_active: bool = False
    cool_ticks_left: int = 0
    wins: int = 0
    losses: int = 0
    trades: int = 0
    ticks: int = 0


def _ewma(prev: float, new_val: float, span: float) -> float:
    """O(1) EWMA update."""
    if span <= 1.0:
        return new_val
    alpha = 2.0 / (span + 1.0)
    return alpha * new_val + (1.0 - alpha) * prev


class StrategyBase:
    """Base interface every auto-gen strategy must implement."""

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        self.config: Dict[str, Any] = dict(DEFAULT_CONFIG)
        if config:
            self.config.update(config)
        self.validate_config()
        self.reset()

    def reset(self) -> None:
        self.state = EngineState()
        self.state.free_quote = float(self.config["capital"])
        self.state.total_equity = float(self.config["capital"])
        self.state.equity_hwm = float(self.config["capital"])
        self._last_log_ret: Optional[float] = None

    def validate_config(self) -> None:
        """Explicit config validation; raises ValueError on bad input."""
        for k in ("fee", "target_vol", "base_spacing_pct", "win_prob_assumed"):
            v = float(self.config[k])
            if v <= 0.0:
                raise ValueError(f"config[{k}] must be > 0, got {v}")
        if not (0.0 < float(self.config["dd_gate"]) < 1.0):
            raise ValueError("dd_gate must be in (0,1)")
        if int(self.config["max_levels"]) < 2:
            raise ValueError("max_levels must be >= 2")
        if not (0.0 < float(self.config["kelly_fraction"]) <= 1.0):
            raise ValueError("kelly_fraction must be in (0,1]")
        if not (0.0 < float(self.config["stop_loss_frac"]) < 1.0):
            raise ValueError("stop_loss_frac must be in (0,1)")

    def estimate_memory_mb(self) -> float:
        """Rough footprint: only scalars + small deque, negligible."""
        return 0.05

    def _update_vol(self, price: float) -> None:
        """O(1) EWMA on |log-returns| as realised volatility estimate."""
        if self._last_log_ret is not None and price > 0.0:
            lr = abs(math.log(price / self._last_log_ret))
            self.state.vol_ewma = _ewma(
                self.state.vol_ewma, lr, float(self.config["vol_ewma_span"])
            )
            self.state.ewm_count += 1
        self._last_log_ret = price

    def _target_size_frac(self) -> float:
        """Asymmetric vol-target Kelly position sizing in [0,1]."""
        cfg = self.config
        vol = float(cfg["min_vol_floor"])
        if self.state.vol_ewma > 0.0:
            vol = min(max(self.state.vol_ewma, float(cfg["min_vol_floor"])),
                      float(cfg["max_vol_ceil"]))
        vol_ratio = float(cfg["target_vol"]) / vol
        size = math.pow(vol_ratio, float(cfg["vol_scale_power"]))
        edge = (2.0 * float(cfg["win_prob_assumed"]) - 1.0)
        kelly = float(cfg["kelly_fraction"]) * max(edge, 0.0)
        return max(0.05, min(size * (1.0 + kelly), 0.95))

    def on_tick(self, price: float, free_quote: float,
                total_equity: float) -> Dict[str, Any]:
        """Classic grid producer on each price tick."""
        st = self.state
        cfg = self.config
        st.ticks += 1
        st.free_quote = free_quote
        st.total_equity = total_equity
        st.equity_hwm = max(st.equity_hwm, total_equity)

        dd = 1.0 - (total_equity / st.equity_hwm) if st.equity_hwm > 0 else 0.0
        if dd >= float(cfg["dd_gate"]):
            st.dd_active = True
            st.cool_ticks_left = int(cfg["dd_reentry_cool"])
        elif st.cool_ticks_left > 0:
            st.cool_ticks_left -= 1
        elif st.cool_ticks_left == 0:
            st.dd_active = False

        if price <= 0.0 or st.halt or st.dd_active:
            return {"action": "hold"}

        self._update_vol(price)
        size_frac = self._target_size_frac()
        spacing = float(cfg["base_spacing_pct"]) / max(size_frac, 0.05)
        st.levels = int(cfg["max_levels"])
        st.spacing = spacing
        st.regime = "vtk_vol={:.5f}_size={:.2f}".format(st.vol_ewma, size_frac)

        if st.last_price is None:
            st.last_price = price
            st.pending.append(price * (1.0 - spacing))
            return {"action": "hold", "spacing": spacing,
                    "levels": st.levels, "size_frac": size_frac}

        cap = int(cfg.get("pending_cap", MAX_PENDING_LEVELS))
        if len(st.pending) >= cap:
            st.halt = True
            return {"action": "halt", "reason": "pending_cap",
                    "levels": len(st.pending), "spacing": spacing}
        lowest = st.pending[0] if st.pending else st.last_price
        if price <= lowest * (1.0 - spacing):
            qty = (free_quote * size_frac) / price
            st.pending.append(price * (1.0 - spacing))
            return {"action": "buy", "price": price, "qty": qty,
                    "spacing": spacing, "levels": st.levels}

        hwm = st.pending[-1] if st.pending else st.last_price
        if price >= hwm * (1.0 + spacing) and len(st.pending) > 1:
            ref = st.pending.popleft()
            st.pending.append(price * (1.0 + spacing))
            return {"action": "sell", "price": price,
                    "spacing": spacing, "levels": st.levels}
        return {"action": "hold", "spacing": spacing, "levels": st.levels}

    def on_fill(self, side: str, price: float, qty: float,
                realized_pnl: float = 0.0) -> None:
        """Bookkeeping on fills; explicit error handling."""
        st = self.state
        st.position_fills += 1
        st.trades += 1
        st.realised_pnl += realized_pnl
        if realized_pnl >= 0.0:
            st.wins += 1
        else:
            st.losses += 1
        if side not in ("buy", "sell"):
            raise ValueError("on_fill: unknown side {!r}".format(side))


def main() -> None:
    """Inline self-test on small synthetic data."""
    strat = StrategyBase({"capital": 3.7, "fee": 0.0016})
    assert strat.estimate_memory_mb() <= 0.1
    price = 0.10
    equity = 3.7
    actions = {"buy": 0, "sell": 0, "hold": 0}
    for _ in range(20000):
        price *= (1.0 + 0.0005 * (-1 if _ % 3 == 0 else 1))
        r = strat.on_tick(price, strat.state.free_quote, equity)
        a = r.get("action", "hold")
        actions[a] = actions.get(a, 0) + 1
        if a == "buy":
            strat.on_fill("buy", price, r.get("qty", 0.0), 0.001)
        elif a == "sell":
            strat.on_fill("sell", price, 0.0, 0.002)
    assert len(strat.state.pending) <= int(strat.config["pending_cap"]) + 2
    print("VTK-GAR self-test OK: ticks={} trades={} wins={} "
          "losses={} actions={}".format(
              strat.state.ticks, strat.state.trades,
              strat.state.wins, strat.state.losses, actions))
    strat = None
    gc.collect()


if __name__ == "__main__":
    main()
