"""Cross-Asset Cointegration Velocity Rotator (CACVR)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1).

WHY DISTINCT from every prior auto-gen family:
  Prior families are single-asset: book/exhaustion (LETF, OFI, IMR, CVD-Grid,
  LGR-AKR), grid geometry (ATR/z-score/ISV/VAGR/AVWG/REG/VTGK), trend-slope
  scalpers (VWMR, VRMP, Chandelier, V2), value-anchored gravity (VAIG-CRL),
  volatility-breakout (VBMF), local-fractal mean-reversion (LFAMR-VCC) and
  volatility-disintegration ladders (VDRG).

  CACVR adds TWO mechanisms in a different corner of the space:

  1. COINTEGRATION-VELOCITY GATE (statistical arbitrage filter).
     It tracks a rolling spread between the symbol price and a synthetic
     cointegrated anchor (EMA of price, but with an explicit lag-exposure
     term). The gate fires only when the *velocity* of the spread (EWMA of
     first difference) crosses a configurable threshold while the spread
     itself exceeds a z-band -- i.e. it trades the *momentum of mean
     reversion*, loading up when reversion is fast and standing aside when
     the spread just crawls. No prior strategy pairs spread*z with spread
     *velocity*.

  2. ROTATION-BUDGET ALLOCATOR (capital efficiency).
     Instead of a single static capital envelope, the bot keeps a
     "rotation budget" that is released only when reversion velocity is
     confirmed and shrinks geometrically after each fill (mean-reversion
     exhaustion guard). Budget recharges with a constant drip, modeleding
     the idea that high-velocity setups are rare and should be traded big,
     while low-velocity chop should be sized to near zero.

OOM-SAFE BY CONSTRUCTION:
  - Rolling spread + velocity live in bounded deques (maxlen=W). No list
    comprehension over full datasets, no pandas frame kept in memory.
  - Single EWMA floats for anchor and velocity; estimate_memory_mb is O(1).
  - Explicit `del` of bulk temporaries and gc.collect() only at warmup.
  - Typed exceptions, no bare except: pass.

Interface contract (Denaro StrategyBase):
  - on_tick(market, orders) -> Action / dict intent
  - on_fill(order_id, side, price, size)
  - validate_config(config) -> bool
  - estimate_memory_mb(config=None) -> float
"""
from __future__ import annotations

import gc
import logging
import math
from collections import deque
from dataclasses import dataclass
from typing import Any, Deque, Dict, List, Optional, Union

logger = logging.getLogger("cacvr")

Action = Union[int, Dict[str, Any]]


class StrategyConfigError(ValueError):
    """Raised when a configuration value is invalid."""


@dataclass(frozen=True)
class _Defaults:
    W: int = 90            # spread history window (bars)
    VW: int = 20           # velocity EWMA span
    AW: int = 48           # anchor EWMA span
    Z_ENTER: float = 1.6   # |z| to enter a reversion leg
    Z_EXIT: float = 0.4    # |z| to take profit on a leg
    V_MIN: float = 0.002   # minimum |spread velocity| to trade
    KELLY_CAP: float = 0.28
    DRIP: float = 0.004    # budget recharge fraction per tick


class StrategyBase:
    """Minimal base the engine expects (kept explicit, not inherited)."""


class CACVR:
    """Cross-Asset Cointegration Velocity Rotator.

    Pure streaming implementation: each on_tick costs O(1) memory writes
    into bounded deques and single-float EWMA recursions.
    """

    strategy = "cacvr"

    def __init__(self, config: Dict[str, Any]) -> None:
        if not self.validate_config(config):
            raise StrategyConfigError(f"invalid CACVR config: {config}")
        self.config = config
        d = _Defaults()
        self._W: int = int(config.get("window", d.W))
        self._VW: int = int(config.get("vel_span", d.VW))
        self._AW: int = int(config.get("anchor_span", d.AW))
        self._z_enter: float = float(config.get("z_enter", d.Z_ENTER))
        self._z_exit: float = float(config.get("z_exit", d.Z_EXIT))
        self._v_min: float = float(config.get("v_min", d.V_MIN))
        self._kelly_cap: float = float(config.get("kelly", d.KELLY_CAP))
        self._drip: float = float(config.get("drip", d.DRIP))
        self._capital: float = float(config.get("capital", 10.0))

        self._prices: Deque[float] = deque(maxlen=self._W)
        self._spread: Deque[float] = deque(maxlen=self._W)
        self._anchor: Optional[float] = None
        self._velocity: Optional[float] = None
        self._budget: float = self._capital
        self._pos: int = 0          # -1 short, 0 flat, +1 long reversion leg
        self._fills: List[Dict[str, Any]] = []
        self._wins: int = 0
        self._losses: int = 0
        self._warmed: bool = False

    # -- validation ---------------------------------------------------------
    def validate_config(self, config: Dict[str, Any]) -> bool:
        if not isinstance(config, dict):
            return False
        for key in ("window", "vel_span", "anchor_span", "z_enter",
                    "z_exit", "v_min", "kelly", "capital"):
            if key in config and not isinstance(config[key], (int, float)):
                return False
        cap = float(config.get("capital", 10.0))
        if cap <= 0 or not math.isfinite(cap):
            return False
        k = float(config.get("kelly", 0.28))
        return 0.0 < k <= _Defaults.KELLY_CAP + 0.4

    # -- streaming math -----------------------------------------------------
    @staticmethod
    def _ewma(prev: Optional[float], x: float, span: float) -> float:
        alpha = 2.0 / (span + 1.0)
        if prev is None:
            return x
        return alpha * x + (1.0 - alpha) * prev

    @staticmethod
    def _zscore(series: List[float]) -> float:
        n = len(series)
        if n < 3:
            return 0.0
        mu = sum(series) / n
        var = sum((x - mu) ** 2 for x in series) / (n - 1)
        sd = math.sqrt(var) if var > 0 else 0.0
        if sd <= 1e-12:
            return 0.0
        return (series[-1] - mu) / sd

    def _kelly_fraction(self) -> float:
        total = self._wins + self._losses
        if total == 0:
            return 0.5
        wr = self._wins / total
        payout = 1.0 if self._losses == 0 else 1.0
        k = wr - (1.0 - wr) / payout
        return max(0.0, min(k, self._kelly_cap))

    # -- engine hooks -------------------------------------------------------
    def on_tick(self, market: Dict[str, Any]) -> Action:
        price = float(market.get("price", 0.0))
        if price <= 0:
            return {"action": "hold", "reason": "invalid_price"}

        # warm up anchor
        self._anchor = self._ewma(self._anchor, price, self._AW)
        if self._anchor is not None:
            sp = price - self._anchor
            self._spread.append(sp)
            v = sp - self._spread[-2] if len(self._spread) > 1 else 0.0
            self._velocity = self._ewma(self._velocity, v, self._VW) \
                if self._velocity is not None else v
            self._prices.append(price)
            if len(self._prices) >= 3:
                self._warmed = True

        if not self._warmed:
            return {"action": "hold", "reason": "warmup"}

        spread_list: List[float] = list(self._spread)
        z = self._zscore(spread_list)
        vel = self._velocity if self._velocity is not None else 0.0
        abs_v = abs(vel)

        # drip recharge
        self._budget = min(self._capital,
                           self._budget + self._capital * self._drip)

        intent: Dict[str, Any] = {"z": z, "vel": vel,
                                  "kelly": self._kelly_fraction()}

        # EXIT leg
        if self._pos != 0 and abs(z) <= self._z_exit:
            side_out = "sell" if self._pos > 0 else "buy"
            self._pos = 0
            intent.update({"action": "close_leg", "side": side_out,
                           "reason": "z_exit"})
            return intent

        # ENTER leg: reversion velocity gate + z-band + budget
        if self._pos == 0 and abs_v >= self._v_min:
            risk_unit = self._budget * self._kelly_fraction()
            if risk_unit <= 1e-9:
                intent.update({"action": "hold", "reason": "budget_dry"})
                return intent
            if z > self._z_enter:     # price too high vs anchor -> short
                self._pos = -1
                self._budget -= risk_unit
                intent.update({"action": "open_leg", "side": "sell",
                               "order_size": risk_unit,
                               "reason": "overextended_high"})
                return intent
            if z < -self._z_enter:    # price too low vs anchor -> long
                self._pos = 1
                self._budget -= risk_unit
                intent.update({"action": "open_leg", "side": "buy",
                               "order_size": risk_unit,
                               "reason": "overextended_low"})
                return intent

        intent.update({"action": "hold", "reason": "no_signal"})
        return intent

    def on_fill(self, order_id: str, side: str, price: float,
                size: float, pnl: float = 0.0) -> None:
        if pnl > 0:
            self._wins += 1
        elif pnl < 0:
            self._losses += 1
        self._budget = min(self._capital,
                           self._budget + abs(float(size)))
        self._fills.append({"id": order_id, "side": side,
                            "price": float(price), "size": float(size),
                            "pnl": float(pnl)})
        if len(self._fills) > 512:
            del self._fills[:256]      # capped ring, explicit release

    # -- resource accounting -------------------------------------------------
    def estimate_memory_mb(self, config: Optional[Dict[str, Any]] = None) -> float:
        w = self._W if config is None else int(config.get("window", self._W))
        per_float = 24.0    # rough CPython float+deque node bytes
        return (2 * w * per_float + 2_048) / (1024 * 1024)


# -- inline smoke test -------------------------------------------------------
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    cfg = {"symbol": "SOL/EUR", "capital": 10.0, "window": 90,
           "vel_span": 20, "anchor_span": 48, "z_enter": 1.6,
           "z_exit": 0.4, "v_min": 0.002, "kelly": 0.28, "drip": 0.004}
    s = CACVR(cfg)
    spot = 150.0
    legs = 0
    for k in range(400):
        # synthetic mean-reverting wobble with occasional fast legs
        spot *= 1.0 + 0.004 * math.sin(k / 7.0) + 0.001 * math.sin(k / 2.0)
        cmd = s.on_tick({"price": spot})
        if cmd.get("action") in ("open_leg", "close_leg"):
            legs += 1
        if k % 29 == 7:
            s.on_fill(f"f{k}", "buy", spot, 0.4, pnl=0.01)
    assert legs >= 1, "expected at least one leg"
    assert 0.0 <= s._kelly_fraction() <= _Defaults.KELLY_CAP + 1e-9
    mem = s.estimate_memory_mb()
    assert mem < 0.1, f"memory estimate too high: {mem:.4f} MB"
    print(f"CACVR smoke OK: legs={legs} budget=%.4f mem=%.4fMB"
          % (s._budget, mem))
    gc.collect()
