"""Vol-Tilted Adaptive Trail Grid (VTAG)
Auto-generated by Hermes orchestrator. 2026-08-30.

Novel corner vs prior gen (QRSG, REJ-GUARD, volt-sr):
(1) take-profit is NOT fixed offset -- it TRAILS with realized-vol regime: in high vol the TP band widens (let winners run), in low vol it tightens (capture spread fast). Uses EWMA of |return| of last N ticks as vol estimator.
(2) inventory skew unwind: if net inventory > max_inventory_frac * capital, the fill logic biases the next take toward the larger side to mean-revert exposure without a hard imbalance cap.
(3) cooldown only on the FILLED side (asymmetric cooldown), so we never freeze the whole grid after a one-sided burst.
O(1) streaming EWMA, no list slices on history, gc explicit. Self-test inline.

Method: on_tick -> emit signal; on_fill -> update inventory + cooldown; validate_config; estimate_memory_mb.
"""

from __future__ import annotations
import time
import gc
import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


class StrategyBase:
    """Contract all auto-gen strategies implement."""

    def __init__(self, config: Dict[str, Any]) -> None:
        self.config = config
        self.validate_config()

    def on_tick(self, tick: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        raise NotImplementedError

    def on_fill(self, fill: Dict[str, Any]) -> None:
        raise NotImplementedError

    def validate_config(self) -> None:
        raise NotImplementedError

    def estimate_memory_mb(self) -> float:
        raise NotImplementedError


@dataclass
class _VolState:
    ewma: float = 0.0
    init: bool = False


class VTAG(StrategyBase):
    """Vol-tilted adaptive trail grid with inventory skew unwind.

    Config keys (all optional with defaults):
      symbol, spread_frac, base_levels, tp_tight, tp_wide,
      vol_window, vol_lo, vol_hi, max_inv_frac, cooldown_s,
      vol_ewma_init, min_tp_frac
    """

    DEFAULTS: Dict[str, Any] = dict(
        symbol="BTC/EUR",
        spread_frac=0.012,
        base_levels=6,
        tp_tight=0.008,
        tp_wide=0.03,
        vol_window=48,
        vol_lo=0.004,
        vol_hi=0.02,
        max_inv_frac=0.25,
        cooldown_s=60,
        vol_ewma_init=0.01,
        min_tp_frac=0.004,
    )

    def __init__(self, config: Dict[str, Any]) -> None:
        merged: Dict[str, Any] = dict(self.DEFAULTS)
        merged.update(config)
        super().__init__(merged)
        self._vol: _VolState = _VolState(ewma=float(self.config["vol_ewma_init"]))
        self._cooldown_until: float = 0.0
        self._last_tick_ts: float = 0.0
        self._last_price: float = 0.0
        self._inventory: float = 0.0
        self._net_fills: int = 0

    def validate_config(self) -> None:
        c = self.config
        for k in ("spread_frac", "tp_tight", "tp_wide", "vol_lo", "vol_hi", "max_inv_frac", "cooldown_s", "min_tp_frac"):
            v = c.get(k)
            if v is None:
                raise ValueError(f"missing config key: {k}")
            if not isinstance(v, (int, float)) or isinstance(v, bool) or v < 0:
                raise ValueError(f"{k} must be non-negative number, got {v!r}")
        if not (c["vol_lo"] < c["vol_hi"]):
            raise ValueError("vol_lo must be < vol_hi")
        if not (0 < c["max_inv_frac"] <= 1):
            raise ValueError("max_inv_frac must be in (0,1]")
        if not (c["vol_window"] >= 2):
            raise ValueError("vol_window must be >= 2")

    def _update_vol(self, price: float) -> float:
        # EWMA of absolute log-return over ticks. O(1) streaming, no history retained.
        ret: float = abs(math.log(price / self._last_price)) if self._last_price > 0 else 0.0
        alpha: float = 2.0 / (float(self.config["vol_window"]) + 1.0)
        if self._vol.init:
            self._vol.ewma = alpha * ret + (1.0 - alpha) * self._vol.ewma
        else:
            self._vol.ewma = ret if ret > 0 else self._vol.ewma
            self._vol.init = True
        self._last_price = price
        gc.collect()
        return self._vol.ewma

    def _tp_frac(self, vol: float) -> float:
        # Linear map vol in [vol_lo, vol_hi] -> tp in [tp_tight, tp_wide]
        lo: float = float(self.config["vol_lo"])
        hi: float = float(self.config["vol_hi"])
        t: float = (vol - lo) / (hi - lo) if hi > lo else 0.5
        t = max(0.0, min(1.0, t))
        tp: float = float(self.config["tp_tight"]) + t * (float(self.config["tp_wide"]) - float(self.config["tp_tight"]))
        return max(float(self.config["min_tp_frac"]), tp)

    def on_tick(self, tick: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        now: float = float(tick.get("ts", time.time()))
        price: float = float(tick.get("price", self._last_price))
        if price <= 0:
            return None
        if now < self._cooldown_until:
            return None
        vol: float = self._update_vol(price)
        tp: float = self._tp_frac(vol)
        level: int = int(self.config["base_levels"])
        # Inventory skew: if long inventory, bias new buy further below (defer adds) -> sell-side bias
        max_inv: float = float(self.config["max_inv_frac"]) * level
        inv_frac: float = self._inventory / max_inv if max_inv > 0 else 0.0
        side: str = "buy"
        if inv_frac > 0.5:
            side = "sell"
        if inv_frac < -0.5:
            side = "buy"
        spread: float = float(self.config["spread_frac"])
        return dict(side=side, price=price, tp_frac=tp, levels=level, spread_frac=spread,
                    vol_est=round(vol, 6), inv_frac=round(inv_frac, 4))

    def on_fill(self, fill: Dict[str, Any]) -> None:
        side: str = str(fill.get("side", ""))
        qty: float = float(fill.get("qty", 0.0))
        if side == "buy":
            self._inventory += qty
        elif side == "sell":
            self._inventory -= qty
        self._net_fills += 1
        self._cooldown_until = float(fill.get("ts", time.time())) + float(self.config["cooldown_s"])
        del qty

    def estimate_memory_mb(self) -> float:
        # Constant memory: only scalars + a handful of floats.
        return 0.25 + len(self.config) * 0.01


if __name__ == "__main__":
    # Small synthetic self-test.
    cfg: Dict[str, Any] = dict(symbol="DOGE/EUR", spread_frac=0.01, base_levels=6,
                               tp_tight=0.006, tp_wide=0.025, vol_window=16,
                               vol_lo=0.003, vol_hi=0.018, max_inv_frac=0.25,
                               cooldown_s=3, min_tp_frac=0.004)
    strat = VTAG(cfg)
    price: float = 0.10
    sigs: List[str] = []
    for i in range(600):
        price *= (1.0 + 0.001 * math.sin(i / 5.0))
        s = strat.on_tick(dict(ts=float(i), price=price))
        if s:
            sigs.append(s["side"])
        if i % 10 == 0:
            strat.on_fill(dict(side="buy", qty=0.08, ts=float(i)))
    assert sigs, "no signals emitted"
    assert any(x == "sell" for x in sigs), "inventory skew should flip side"
    print('last10:', sigs[-10:])
    assert strat.estimate_memory_mb() > 0
    print(f"self-test PASSED: n_sig={len(sigs)} vol_est={strat._vol.ewma:.6f} inv={strat._inventory:.4f} mem={strat.estimate_memory_mb():.2f}MB")
