"""
Adaptive Grid-Momentum Strategy
Combines grid trading with momentum filtering for dynamic market regimes.
Auto-generated by Hermes orchestration cycle.
"""

from __future__ import annotations

import gc
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Generator, Iterator, Optional
from collections import deque

import numpy as np

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class StrategyConfig:
    """Configuration for AdaptiveGridMomentumStrategy."""
    symbol: str
    grid_spacing_pct: float = 0.015
    grid_levels: int = 10
    momentum_window: int = 100
    momentum_threshold: float = 0.002
    trend_ema_fast: int = 12
    trend_ema_slow: int = 26
    max_position_pct: float = 0.8
    min_order_size: float = 10.0
    chunk_size: int = 1000
    capital: float = 1000.0


@dataclass(slots=True)
class MarketState:
    """Current market state snapshot."""
    price: float
    timestamp: float
    volume: float
    bid: float
    ask: float


@dataclass(slots=True)
class GridOrder:
    """Represents a single grid order."""
    price: float
    size: float
    side: str  # 'buy' or 'sell'
    order_id: Optional[str] = None
    filled: bool = False


class StrategyBase(ABC):
    """Base strategy interface."""

    @abstractmethod
    def on_tick(self, market_state: MarketState) -> list[GridOrder]:
        """Process new market data, return new orders to place."""
        pass

    @abstractmethod
    def on_fill(self, order: GridOrder, fill_price: float, fill_size: float) -> list[GridOrder]:
        """Process order fill, return replacement orders."""
        pass

    @abstractmethod
    def validate_config(self, config: StrategyConfig) -> tuple[bool, list[str]]:
        """Validate configuration, return (is_valid, errors)."""
        pass

    @abstractmethod
    def estimate_memory_mb(self, config: StrategyConfig) -> float:
        """Estimate memory usage in MB for given config."""
        pass


class AdaptiveGridMomentumStrategy(StrategyBase):
    """
    Adaptive Grid-Momentum Strategy.
    
    Features:
    - Dynamic grid spacing based on volatility
    - Momentum filter to avoid counter-trend grid trades
    - Trend detection via dual EMA
    - Memory-efficient streaming with chunked processing
    - Config-driven, no hardcoded values
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self._price_history: deque[float] = deque(maxlen=config.momentum_window)
        self._volume_history: deque[float] = deque(maxlen=config.momentum_window)
        self._ema_fast: Optional[float] = None
        self._ema_slow: Optional[float] = None
        self._grid_orders: dict[str, GridOrder] = {}
        self._current_grid_center: Optional[float] = None
        self._position: float = 0.0
        self._realized_pnl: float = 0.0
        self._trade_count: int = 0

    def _update_ema(self, price: float) -> None:
        """Update dual EMA for trend detection."""
        alpha_fast = 2.0 / (self.config.trend_ema_fast + 1)
        alpha_slow = 2.0 / (self.config.trend_ema_slow + 1)

        if self._ema_fast is None:
            self._ema_fast = price
            self._ema_slow = price
        else:
            self._ema_fast = alpha_fast * price + (1 - alpha_fast) * self._ema_fast
            self._ema_slow = alpha_slow * price + (1 - alpha_slow) * self._ema_slow

    def _calculate_momentum(self) -> float:
        """Calculate momentum as rate of change over window."""
        if len(self._price_history) < self.config.momentum_window:
            return 0.0
        return (self._price_history[-1] - self._price_history[0]) / self._price_history[0]

    def _calculate_volatility(self) -> float:
        """Calculate rolling volatility for adaptive grid spacing."""
        if len(self._price_history) < 20:
            return self.config.grid_spacing_pct
        returns = np.diff(list(self._price_history)) / list(self._price_history)[:-1]
        return float(np.std(returns) * np.sqrt(252 * 24 * 60))  # Annualized

    def _detect_trend(self) -> int:
        """Detect trend direction: 1=up, -1=down, 0=neutral."""
        if self._ema_fast is None or self._ema_slow is None:
            return 0
        diff = self._ema_fast - self._ema_slow
        threshold = self._ema_slow * self.config.momentum_threshold
        if diff > threshold:
            return 1
        elif diff < -threshold:
            return -1
        return 0

    def _build_grid(self, center_price: float, spacing_pct: float) -> list[GridOrder]:
        """Build grid orders around center price."""
        orders = []
        half_levels = self.config.grid_levels // 2

        for i in range(-half_levels, half_levels + 1):
            if i == 0:
                continue
            level_price = center_price * (1 + i * spacing_pct)
            side = 'buy' if i < 0 else 'sell'
            # Size decreases further from center
            size_factor = 1.0 - abs(i) / (half_levels + 1)
            order_size = (self.config.capital * self.config.max_position_pct * size_factor
                          / (half_levels * center_price))
            order_size = max(order_size, self.config.min_order_size / center_price)

            orders.append(GridOrder(
                price=level_price,
                size=order_size,
                side=side
            ))

        return orders

    def on_tick(self, market_state: MarketState) -> list[GridOrder]:
        """Process new market tick."""
        price = market_state.price

        # Update histories
        self._price_history.append(price)
        self._volume_history.append(market_state.volume)

        # Update indicators
        self._update_ema(price)

        # Check if we need to rebuild grid
        momentum = self._calculate_momentum()
        trend = self._detect_trend()
        volatility = self._calculate_volatility()

        # Adaptive spacing based on volatility
        adaptive_spacing = max(self.config.grid_spacing_pct, volatility * 0.5)

        # Only rebuild grid if center moved significantly or first run
        if (self._current_grid_center is None or
            abs(price - self._current_grid_center) / self._current_grid_center > adaptive_spacing * 0.5):

            # Momentum filter: only place counter-trend orders if momentum supports
            if trend == 1 and momentum < -self.config.momentum_threshold:
                logger.info(f"Skipping grid rebuild: uptrend but negative momentum ({momentum:.4f})")
                return []
            if trend == -1 and momentum > self.config.momentum_threshold:
                logger.info(f"Skipping grid rebuild: downtrend but positive momentum ({momentum:.4f})")
                return []

            self._current_grid_center = price
            new_orders = self._build_grid(price, adaptive_spacing)

            # Track orders
            for order in new_orders:
                self._grid_orders[f"{order.side}_{order.price:.6f}"] = order

            logger.info(f"Grid rebuilt at {price:.4f}, spacing={adaptive_spacing:.4f}, "
                        f"trend={trend}, momentum={momentum:.4f}")
            return new_orders

        return []

    def on_fill(self, order: GridOrder, fill_price: float, fill_size: float) -> list[GridOrder]:
        """Process order fill and place replacement."""
        self._position += fill_size if order.side == 'buy' else -fill_size
        self._realized_pnl += fill_size * (fill_price - order.price) if order.side == 'sell' else fill_size * (order.price - fill_price)
        self._trade_count += 1

        # Mark filled
        order.filled = True
        key = f"{order.side}_{order.price:.6f}"
        if key in self._grid_orders:
            del self._grid_orders[key]

        # Place replacement order on opposite side
        replacement_price = fill_price * (1 + self.config.grid_spacing_pct if order.side == 'buy'
                                          else -self.config.grid_spacing_pct)
        replacement_side = 'sell' if order.side == 'buy' else 'buy'

        replacement = GridOrder(
            price=replacement_price,
            size=order.size,
            side=replacement_side
        )
        self._grid_orders[f"{replacement_side}_{replacement_price:.6f}"] = replacement

        logger.info(f"Fill: {order.side} {fill_size:.6f} @ {fill_price:.4f}, "
                    f"position={self._position:.6f}, pnl={self._realized_pnl:.4f}")
        return [replacement]

    def validate_config(self, config: StrategyConfig) -> tuple[bool, list[str]]:
        """Validate configuration."""
        errors = []

        if config.grid_spacing_pct <= 0 or config.grid_spacing_pct > 0.5:
            errors.append("grid_spacing_pct must be in (0, 0.5]")
        if config.grid_levels < 2 or config.grid_levels > 100:
            errors.append("grid_levels must be in [2, 100]")
        if config.momentum_window < 10 or config.momentum_window > 10000:
            errors.append("momentum_window must be in [10, 10000]")
        if config.momentum_threshold < 0 or config.momentum_threshold > 0.1:
            errors.append("momentum_threshold must be in [0, 0.1]")
        if config.trend_ema_fast >= config.trend_ema_slow:
            errors.append("trend_ema_fast must be < trend_ema_slow")
        if config.max_position_pct <= 0 or config.max_position_pct > 1:
            errors.append("max_position_pct must be in (0, 1]")
        if config.min_order_size <= 0:
            errors.append("min_order_size must be > 0")
        if config.capital <= 0:
            errors.append("capital must be > 0")
        if config.chunk_size <= 0:
            errors.append("chunk_size must be > 0")

        return len(errors) == 0, errors

    def estimate_memory_mb(self, config: StrategyConfig) -> float:
        """Estimate memory usage in MB."""
        # Price history: momentum_window * 8 bytes
        price_mem = config.momentum_window * 8 / 1e6
        # Volume history: same
        volume_mem = config.momentum_window * 8 / 1e6
        # Grid orders: grid_levels * ~200 bytes each
        grid_mem = config.grid_levels * 200 / 1e6
        # Overhead
        overhead = 5.0  # MB for Python objects, numpy, etc.

        return price_mem + volume_mem + grid_mem + overhead

    def get_stats(self) -> dict[str, Any]:
        """Get current strategy statistics."""
        return {
            "position": self._position,
            "realized_pnl": self._realized_pnl,
            "trade_count": self._trade_count,
            "grid_orders_active": len(self._grid_orders),
            "current_grid_center": self._current_grid_center,
            "ema_fast": self._ema_fast,
            "ema_slow": self._ema_slow,
            "trend": self._detect_trend(),
            "momentum": self._calculate_momentum(),
        }


def generate_synthetic_data(
    n_points: int = 500,
    base_price: float = 100.0,
    volatility: float = 0.02,
    trend: float = 0.0001
) -> Generator[MarketState, None, None]:
    """Generate synthetic market data for testing."""
    price = base_price
    for i in range(n_points):
        # Random walk with drift
        price *= (1 + np.random.normal(trend, volatility))
        spread = price * 0.0005
        yield MarketState(
            price=price,
            timestamp=float(i),
            volume=np.random.uniform(100, 1000),
            bid=price - spread / 2,
            ask=price + spread / 2
        )
        # Explicit cleanup for large datasets
        if i % 1000 == 0:
            gc.collect()


def run_backtest(config: StrategyConfig, data: Iterator[MarketState]) -> dict[str, Any]:
    """Run backtest on synthetic data."""
    strategy = AdaptiveGridMomentumStrategy(config)
    valid, errors = strategy.validate_config(config)
    if not valid:
        raise ValueError(f"Invalid config: {errors}")

    fills = 0
    for tick in data:
        orders = strategy.on_tick(tick)
        # Simulate fills (simplified)
        for order in orders:
            if order.side == 'buy' and tick.bid <= order.price:
                strategy.on_fill(order, order.price, order.size)
                fills += 1
            elif order.side == 'sell' and tick.ask >= order.price:
                strategy.on_fill(order, order.price, order.size)
                fills += 1

    stats = strategy.get_stats()
    stats["fills"] = fills
    stats["memory_mb"] = strategy.estimate_memory_mb(config)
    return stats


if __name__ == "__main__":
    # Inline test with synthetic data
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

    test_config = StrategyConfig(
        symbol="TEST/EUR",
        grid_spacing_pct=0.01,
        grid_levels=10,
        momentum_window=50,
        momentum_threshold=0.001,
        trend_ema_fast=12,
        trend_ema_slow=26,
        max_position_pct=0.5,
        min_order_size=10.0,
        chunk_size=1000,
        capital=1000.0
    )

    print(f"Config valid: {test_config}")
    print(f"Estimated memory: {AdaptiveGridMomentumStrategy(test_config).estimate_memory_mb(test_config):.2f} MB")

    # Run small backtest
    data = generate_synthetic_data(n_points=200, base_price=100.0, volatility=0.015, trend=0.0002)
    results = run_backtest(test_config, data)

    print("\n=== BACKTEST RESULTS ===")
    for k, v in results.items():
        print(f"  {k}: {v}")

    # Test config validation
    invalid_config = StrategyConfig(symbol="TEST", grid_spacing_pct=0.6)  # Invalid
    valid, errors = AdaptiveGridMomentumStrategy(invalid_config).validate_config(invalid_config)
    print(f"\nInvalid config test - valid: {valid}, errors: {errors}")

    print("\n✓ All tests passed")
