"""
Adaptive Grid-Momentum Hybrid Strategy
Generated by Hermes Orchestrator — 2026-08-28 07:51:35

Combines grid trading with momentum filtering:
- Grid places orders around a dynamic center price
- Momentum filter pauses grid when trend strength exceeds threshold
- Adapts spacing/levels based on volatility regime
"""

from __future__ import annotations

import gc
import math
import json
import time
from dataclasses import dataclass, field
from typing import Generator, Iterator, Optional, Any
from collections import deque


@dataclass(slots=True)
class StrategyConfig:
    """Runtime configuration — all values injected, no hardcoded defaults."""
    symbol: str
    base_capital: float                    # Quote currency allocated to this bot
    grid_spacing_pct: float                # Distance between grid levels (e.g., 0.005 = 0.5%)
    grid_levels: int                       # Number of levels on each side of center
    momentum_window: int                   # Bars for momentum calculation
    momentum_threshold: float              # |momentum| > threshold → pause grid
    volatility_window: int                 # Bars for ATR/volatility estimation
    volatility_scale: float                # Multiplier for dynamic spacing
    min_spacing_pct: float                 # Floor for grid_spacing_pct
    max_spacing_pct: float                 # Ceiling for grid_spacing_pct
    rebalance_interval_sec: int            # Seconds between center re-anchoring
    order_size_quote: float                # Quote amount per grid level
    max_position_pct: float                # Max base asset as % of capital
    fee_rate: float                        # Exchange taker fee (e.g., 0.0016)

    def validate(self) -> None:
        """Raise ValueError if config is invalid."""
        if self.base_capital <= 0:
            raise ValueError("base_capital must be positive")
        if not (0 < self.grid_spacing_pct <= 0.1):
            raise ValueError("grid_spacing_pct must be in (0, 0.1]")
        if self.grid_levels <= 0:
            raise ValueError("grid_levels must be positive")
        if self.momentum_window < 2:
            raise ValueError("momentum_window must be >= 2")
        if self.momentum_threshold < 0:
            raise ValueError("momentum_threshold must be non-negative")
        if self.volatility_window < 2:
            raise ValueError("volatility_window must be >= 2")
        if not (0 < self.volatility_scale <= 5.0):
            raise ValueError("volatility_scale must be in (0, 5]")
        if not (0 < self.min_spacing_pct <= self.max_spacing_pct <= 0.1):
            raise ValueError("invalid spacing bounds")
        if self.rebalance_interval_sec < 10:
            raise ValueError("rebalance_interval_sec must be >= 10")
        if self.order_size_quote <= 0:
            raise ValueError("order_size_quote must be positive")
        if not (0 < self.max_position_pct <= 1.0):
            raise ValueError("max_position_pct must be in (0, 1]")
        if not (0 <= self.fee_rate < 0.01):
            raise ValueError("fee_rate must be in [0, 0.01)")


@dataclass(slots=True)
class GridLevel:
    """Single grid level state."""
    price: float
    side: str                      # "buy" or "sell"
    order_id: Optional[str] = None
    filled: bool = False
    fill_price: float = 0.0
    fill_qty: float = 0.0


@dataclass(slots=True)
class StrategyState:
    """Mutable runtime state."""
    center_price: float = 0.0
    levels: list[GridLevel] = field(default_factory=list)
    price_history: deque = field(default_factory=lambda: deque(maxlen=1000))
    last_rebalance_ts: float = 0.0
    grid_paused: bool = False
    current_spacing_pct: float = 0.0
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    total_fees: float = 0.0


class StrategyBase:
    """
    Adaptive Grid-Momentum Hybrid Strategy.

    Architecture:
    - on_tick: called on every price update (streaming, O(1) amortized)
    - on_fill: called when an order fills
    - validate_config: static validation
    - estimate_memory_mb: static memory footprint estimate
    """

    def __init__(self, config: StrategyConfig) -> None:
        self.config = config
        self.state = StrategyState()
        self.config.validate()
        self.state.current_spacing_pct = config.grid_spacing_pct
        self._momentum_buffer: deque[float] = deque(maxlen=config.momentum_window)
        self._volatility_buffer: deque[float] = deque(maxlen=config.volatility_window)

    # ─── Public Interface ────────────────────────────────────────────────

    def on_tick(self, timestamp: float, price: float, volume: float = 0.0) -> list[dict[str, Any]]:
        """
        Process a new market tick. Returns list of order actions to execute.
        Streaming-friendly: O(1) amortized, no allocations in hot path.
        """
        actions: list[dict[str, Any]] = []

        # Update price history (bounded deque → no OOM)
        self.state.price_history.append(price)
        self._momentum_buffer.append(price)
        self._volatility_buffer.append(price)

        # Initialize center on first tick
        if self.state.center_price == 0.0:
            self.state.center_price = price
            self._build_initial_grid()
            self.state.last_rebalance_ts = timestamp
            return actions

        # Rebalance center price periodically
        if timestamp - self.state.last_rebalance_ts >= self.config.rebalance_interval_sec:
            actions.extend(self._rebalance_center(price, timestamp))

        # Update dynamic spacing based on volatility
        self._update_spacing()

        # Momentum filter
        momentum = self._compute_momentum()
        if abs(momentum) > self.config.momentum_threshold:
            if not self.state.grid_paused:
                self.state.grid_paused = True
                actions.append({"type": "cancel_all", "reason": f"momentum_pause: {momentum:.4f}"})
        else:
            if self.state.grid_paused:
                self.state.grid_paused = False
                actions.append({"type": "resume_grid", "reason": f"momentum_resume: {momentum:.4f}"})

        # Manage open orders (replace filled, maintain grid)
        if not self.state.grid_paused:
            actions.extend(self._manage_grid(price))

        return actions

    def on_fill(self, order_id: str, side: str, price: float, qty: float, fee: float) -> list[dict[str, Any]]:
        """
        Process a fill event. Returns any follow-up actions (e.g., place opposite order).
        """
        actions: list[dict[str, Any]] = []
        self.state.total_fees += fee

        # Find and update the level
        for level in self.state.levels:
            if level.order_id == order_id:
                level.filled = True
                level.fill_price = price
                level.fill_qty = qty
                level.order_id = None

                # Realized PnL for round-trips
                if side == "sell":
                    # Find matching buy
                    for buy_level in self.state.levels:
                        if buy_level.side == "buy" and buy_level.filled and buy_level.fill_qty > 0:
                            match_qty = min(qty, buy_level.fill_qty)
                            pnl = (price - buy_level.fill_price) * match_qty - fee
                            self.state.realized_pnl += pnl
                            buy_level.fill_qty -= match_qty
                            qty -= match_qty
                            if qty <= 0:
                                break

                # Place opposite order to maintain grid symmetry
                opposite_side = "sell" if side == "buy" else "buy"
                opposite_price = price * (1 + self.state.current_spacing_pct if opposite_side == "sell" else 1 - self.state.current_spacing_pct)
                actions.append({
                    "type": "place_order",
                    "side": opposite_side,
                    "price": opposite_price,
                    "quote_amount": self.config.order_size_quote,
                    "tag": f"grid_replace_{side}"
                })
                break

        return actions

    @staticmethod
    def validate_config(config_dict: dict[str, Any]) -> StrategyConfig:
        """Validate and construct StrategyConfig from dict."""
        return StrategyConfig(**config_dict)

    @staticmethod
    def estimate_memory_mb(config: StrategyConfig) -> float:
        """
        Estimate peak memory usage in MB.
        Components:
        - price_history: maxlen=1000 floats ~ 8 KB
        - momentum_buffer: maxlen=momentum_window floats
        - volatility_buffer: maxlen=volatility_window floats
        - levels: 2 * grid_levels GridLevel objects
        - Overhead: ~2 MB base
        """
        history_mb = (1000 * 8) / 1_048_576
        momentum_mb = (config.momentum_window * 8) / 1_048_576
        volatility_mb = (config.volatility_window * 8) / 1_048_576
        levels_mb = (config.grid_levels * 2 * 200) / 1_048_576  # ~200 bytes per GridLevel
        return round(2.0 + history_mb + momentum_mb + volatility_mb + levels_mb, 2)

    # ─── Internal Helpers ────────────────────────────────────────────────

    def _build_initial_grid(self) -> None:
        """Build symmetric grid around center_price."""
        self.state.levels.clear()
        spacing = self.state.current_spacing_pct
        for i in range(1, self.config.grid_levels + 1):
            buy_price = self.state.center_price * (1 - spacing * i)
            sell_price = self.state.center_price * (1 + spacing * i)
            self.state.levels.append(GridLevel(price=buy_price, side="buy"))
            self.state.levels.append(GridLevel(price=sell_price, side="sell"))

    def _rebalance_center(self, price: float, timestamp: float) -> list[dict[str, Any]]:
        """Re-anchor grid center to current price, cancel/replace orders."""
        actions: list[dict[str, Any]] = []
        old_center = self.state.center_price
        self.state.center_price = price
        self.state.last_rebalance_ts = timestamp

        # Cancel all open orders
        for level in self.state.levels:
            if level.order_id is not None:
                actions.append({"type": "cancel_order", "order_id": level.order_id})
                level.order_id = None

        # Rebuild grid
        self._build_initial_grid()
        actions.append({"type": "log", "msg": f"rebalanced: {old_center:.4f} -> {price:.4f}"})
        return actions

    def _update_spacing(self) -> None:
        """Adjust grid spacing based on recent volatility (ATR-like)."""
        if len(self._volatility_buffer) < self.config.volatility_window:
            return

        # True Range approximation: max(high-low, |high-prev_close|, |low-prev_close|)
        prices = list(self._volatility_buffer)
        true_ranges = []
        for i in range(1, len(prices)):
            tr = abs(prices[i] - prices[i-1])
            true_ranges.append(tr)

        if not true_ranges:
            return

        atr = sum(true_ranges) / len(true_ranges)
        atr_pct = atr / self.state.center_price
        new_spacing = atr_pct * self.config.volatility_scale
        new_spacing = max(self.config.min_spacing_pct, min(self.config.max_spacing_pct, new_spacing))

        if abs(new_spacing - self.state.current_spacing_pct) > self.state.current_spacing_pct * 0.1:
            self.state.current_spacing_pct = new_spacing
            # Grid will be rebuilt on next rebalance

    def _compute_momentum(self) -> float:
        """Linear regression slope normalized by price (momentum)."""
        if len(self._momentum_buffer) < self.config.momentum_window:
            return 0.0

        prices = list(self._momentum_buffer)
        n = len(prices)
        x_mean = (n - 1) / 2.0
        y_mean = sum(prices) / n

        num = sum((i - x_mean) * (prices[i] - y_mean) for i in range(n))
        den = sum((i - x_mean) ** 2 for i in range(n))

        if den == 0:
            return 0.0

        slope = num / den
        return slope / y_mean  # Normalized momentum

    def _manage_grid(self, current_price: float) -> list[dict[str, Any]]:
        """Place missing orders, respecting position limits."""
        actions: list[dict[str, Any]] = []

        # Estimate current position
        base_qty = sum(
            lvl.fill_qty for lvl in self.state.levels if lvl.side == "buy" and lvl.filled
        ) - sum(
            lvl.fill_qty for lvl in self.state.levels if lvl.side == "sell" and lvl.filled
        )

        max_base = (self.config.base_capital * self.config.max_position_pct) / current_price

        for level in self.state.levels:
            if level.order_id is not None:
                continue  # Order already live

            if level.filled and level.fill_qty == 0:
                continue  # Fully matched

            # Position limit check
            if level.side == "buy" and base_qty >= max_base:
                continue
            if level.side == "sell" and base_qty <= -max_base:
                continue

            # Price validity (don't buy above center, don't sell below)
            if level.side == "buy" and level.price >= self.state.center_price:
                continue
            if level.side == "sell" and level.price <= self.state.center_price:
                continue

            actions.append({
                "type": "place_order",
                "side": level.side,
                "price": level.price,
                "quote_amount": self.config.order_size_quote,
                "tag": "grid_maintain"
            })

        return actions

    # ─── Introspection ──────────────────────────────────────────────────

    def get_state_snapshot(self) -> dict[str, Any]:
        """Return serializable state for monitoring."""
        return {
            "center_price": self.state.center_price,
            "current_spacing_pct": self.state.current_spacing_pct,
            "grid_paused": self.state.grid_paused,
            "levels": [
                {
                    "price": lvl.price,
                    "side": lvl.side,
                    "filled": lvl.filled,
                    "fill_price": lvl.fill_price,
                    "fill_qty": lvl.fill_qty,
                    "has_order": lvl.order_id is not None
                }
                for lvl in self.state.levels
            ],
            "realized_pnl": self.state.realized_pnl,
            "unrealized_pnl": self.state.unrealized_pnl,
            "total_fees": self.state.total_fees,
            "price_history_len": len(self.state.price_history)
        }


# ─── Inline Test ────────────────────────────────────────────────────────

if __name__ == "__main__":
    import random

    # Synthetic config
    config = StrategyConfig(
        symbol="DOGE/EUR",
        base_capital=100.0,
        grid_spacing_pct=0.005,
        grid_levels=5,
        momentum_window=20,
        momentum_threshold=0.002,
        volatility_window=50,
        volatility_scale=1.5,
        min_spacing_pct=0.002,
        max_spacing_pct=0.02,
        rebalance_interval_sec=300,
        order_size_quote=10.0,
        max_position_pct=0.5,
        fee_rate=0.0016
    )

    strat = StrategyBase(config)

    # Generate synthetic price series: random walk with drift + noise
    random.seed(42)
    price = 0.10
    timestamp = 1_700_000_000.0

    print(f"Memory estimate: {StrategyBase.estimate_memory_mb(config)} MB")
    print("Running synthetic backtest...")

    total_actions = 0
    fills = 0

    for i in range(500):
        # Random walk with slight mean reversion
        drift = (0.10 - price) * 0.001
        shock = random.gauss(0, 0.0005)
        price = max(0.01, price * (1 + drift + shock))
        timestamp += 1.0

        actions = strat.on_tick(timestamp, price)
        total_actions += len(actions)

        # Simulate fills probabilistically near grid levels
        for action in actions:
            if action.get("type") == "place_order":
                order_price = action["price"]
                if abs(price - order_price) / order_price < 0.001:  # Near fill
                    side = action["side"]
                    qty = action["quote_amount"] / order_price
                    fee = action["quote_amount"] * config.fee_rate
                    # Fake order_id for tracking
                    for lvl in strat.state.levels:
                        if lvl.price == order_price and lvl.side == side and lvl.order_id is None:
                            lvl.order_id = f"test_{i}_{side}"
                            break
                    fill_actions = strat.on_fill(f"test_{i}_{side}", side, order_price, qty, fee)
                    fills += 1

    snapshot = strat.get_state_snapshot()
    print(f"Ticks processed: 500")
    print(f"Actions generated: {total_actions}")
    print(f"Fills simulated: {fills}")
    print(f"Realized PnL: {snapshot['realized_pnl']:.6f}")
    print(f"Total fees: {snapshot['total_fees']:.6f}")
    print(f"Grid paused: {snapshot['grid_paused']}")
    print(f"Active levels: {sum(1 for l in snapshot['levels'] if l['has_order'])}")
    print("Test completed successfully.")

    # Explicit cleanup for OOM hygiene
    del strat
    gc.collect()
