"""
Adaptive Grid Strategy with Volatility-Based Spacing
Auto-generated by Hermes orchestration cycle.
"""
from __future__ import annotations

import gc
import json
import math
import statistics
from dataclasses import dataclass, field
from typing import Generator, Iterator, Literal, Optional

from typing_extensions import Self


@dataclass(frozen=True, slots=True)
class AdaptiveGridConfig:
    """Configuration for AdaptiveGridStrategy."""
    symbol: str
    base_spacing_pct: float = 0.005          # 0.5% base grid spacing
    min_spacing_pct: float = 0.002           # 0.2% minimum
    max_spacing_pct: float = 0.020           # 2.0% maximum
    volatility_window: int = 20              # periods for volatility calc
    volatility_multiplier: float = 1.5       # ATR multiplier for spacing
    levels: int = 10                         # grid levels each side
    capital_per_level: float = 10.0          # quote currency per level
    max_position_pct: float = 0.80           # max 80% capital deployed
    rebalance_threshold_pct: float = 0.10    # rebalance if spacing drifts 10%
    atr_period: int = 14                     # ATR calculation period
    fee_rate: float = 0.0016                 # maker/taker fee (Kraken default)
    enable_dynamic_levels: bool = True       # adjust levels based on vol

    def validate(self) -> None:
        """Validate configuration parameters."""
        if not 0 < self.base_spacing_pct <= 1:
            raise ValueError("base_spacing_pct must be in (0, 1]")
        if not 0 < self.min_spacing_pct <= self.max_spacing_pct <= 1:
            raise ValueError("invalid spacing bounds")
        if self.volatility_window < 5:
            raise ValueError("volatility_window must be >= 5")
        if self.levels < 1:
            raise ValueError("levels must be >= 1")
        if not 0 < self.capital_per_level:
            raise ValueError("capital_per_level must be > 0")
        if not 0 < self.max_position_pct <= 1:
            raise ValueError("max_position_pct must be in (0, 1]")

    @classmethod
    def from_dict(cls, data: dict) -> Self:
        """Create config from dictionary, ignoring unknown keys."""
        known = {f.name for f in dataclass(cls).__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known}
        return cls(**filtered)

    def estimate_memory_mb(self, max_candles: int = 100_000) -> float:
        """Estimate peak memory usage in MB for given candle count."""
        # Price history: float64 * volatility_window
        price_hist_mb = (self.volatility_window * 8) / 1_048_576
        # ATR buffer: float64 * atr_period
        atr_mb = (self.atr_period * 8) / 1_048_576
        # Grid levels: levels * 2 * (price + qty + side) ~ 48 bytes each
        grid_mb = (self.levels * 2 * 48) / 1_048_576
        # Candle buffer if streaming: max_candles * (ohlcv + timestamp) ~ 56 bytes
        candle_mb = (max_candles * 56) / 1_048_576
        return round(price_hist_mb + atr_mb + grid_mb + candle_mb, 2)


@dataclass(slots=True)
class GridLevel:
    """Single grid level with price, quantity, and state."""
    price: float
    quantity: float
    side: Literal["buy", "sell"]
    order_id: Optional[str] = None
    filled: bool = False


class StrategyBase:
    """Base strategy interface."""

    def on_tick(self, price: float, timestamp: float) -> list[dict]:
        """Process new price tick. Return list of order actions."""
        raise NotImplementedError

    def on_fill(self, order_id: str, side: str, price: float, qty: float) -> None:
        """Handle order fill notification."""
        raise NotImplementedError

    def validate_config(self) -> bool:
        """Validate strategy configuration."""
        raise NotImplementedError

    def estimate_memory_mb(self) -> float:
        """Estimate memory usage in MB."""
        raise NotImplementedError


class AdaptiveGridStrategy(StrategyBase):
    """
    Adaptive Grid Strategy that adjusts spacing based on market volatility.
    Uses ATR (Average True Range) to dynamically widen/tighten grid.
    """

    def __init__(self, config: AdaptiveGridConfig) -> None:
        self.config = config
        config.validate()

        self._price_history: list[float] = []
        self._high_history: list[float] = []
        self._low_history: list[float] = []
        self._close_history: list[float] = []
        self._atr_values: list[float] = []
        self._grid_levels: list[GridLevel] = []
        self._center_price: Optional[float] = None
        self._last_rebalance_price: Optional[float] = None
        self._total_deployed: float = 0.0
        self._realized_pnl: float = 0.0

    def _calculate_atr(self, high: float, low: float, close: float) -> float:
        """Calculate True Range and update ATR."""
        if not self._close_history:
            tr = high - low
        else:
            prev_close = self._close_history[-1]
            tr = max(
                high - low,
                abs(high - prev_close),
                abs(low - prev_close)
            )
        self._atr_values.append(tr)
        if len(self._atr_values) > self.config.atr_period:
            self._atr_values.pop(0)

        if len(self._atr_values) < self.config.atr_period:
            return tr
        return statistics.mean(self._atr_values)

    def _compute_dynamic_spacing(self, atr: float, price: float) -> float:
        """Compute grid spacing based on ATR."""
        if price <= 0:
            return self.config.base_spacing_pct

        atr_pct = atr / price
        dynamic_spacing = atr_pct * self.config.volatility_multiplier
        return max(
            self.config.min_spacing_pct,
            min(self.config.max_spacing_pct, dynamic_spacing)
        )

    def _build_grid(self, center_price: float, spacing_pct: float) -> None:
        """Build or rebuild grid levels around center price."""
        self._grid_levels.clear()
        half_levels = self.config.levels

        # Adjust levels count based on volatility if enabled
        if self.config.enable_dynamic_levels:
            vol_ratio = spacing_pct / self.config.base_spacing_pct
            half_levels = max(3, int(self.config.levels / vol_ratio))

        for i in range(1, half_levels + 1):
            buy_price = center_price * (1 - spacing_pct * i)
            sell_price = center_price * (1 + spacing_pct * i)

            qty = self.config.capital_per_level / buy_price

            self._grid_levels.append(GridLevel(
                price=round(buy_price, 6),
                quantity=round(qty, 6),
                side="buy"
            ))
            self._grid_levels.append(GridLevel(
                price=round(sell_price, 6),
                quantity=round(qty, 6),
                side="sell"
            ))

        self._center_price = center_price
        self._last_rebalance_price = center_price

    def _should_rebalance(self, current_price: float, spacing_pct: float) -> bool:
        """Check if grid needs rebalancing."""
        if self._last_rebalance_price is None:
            return True
        drift = abs(current_price - self._last_rebalance_price) / self._last_rebalance_price
        return drift > self.config.rebalance_threshold_pct

    def _stream_candles(self, candles: list[dict]) -> Generator[dict, None, None]:
        """Stream candles to avoid memory buildup on large datasets."""
        for candle in candles:
            yield candle
            # Explicit cleanup hint for large iterations
            if len(candles) > 10_000:
                del candle
                gc.collect()

    def on_tick(self, price: float, timestamp: float) -> list[dict]:
        """Process price tick, update ATR, manage grid."""
        actions = []

        # Initialize center price on first tick
        if self._center_price is None:
            self._center_price = price
            self._build_grid(price, self.config.base_spacing_pct)
            return actions

        # Simulate OHLC from single price (in production, use real candles)
        high = price * 1.001
        low = price * 0.999
        close = price

        self._price_history.append(price)
        self._high_history.append(high)
        self._low_history.append(low)
        self._close_history.append(close)

        # Maintain window
        window = self.config.volatility_window
        if len(self._price_history) > window:
            self._price_history.pop(0)
            self._high_history.pop(0)
            self._low_history.pop(0)
            self._close_history.pop(0)

        # Calculate ATR and dynamic spacing
        atr = self._calculate_atr(high, low, close)
        spacing_pct = self._compute_dynamic_spacing(atr, price)

        # Check rebalance
        if self._should_rebalance(price, spacing_pct):
            self._build_grid(price, spacing_pct)
            actions.append({
                "type": "rebalance",
                "center_price": price,
                "spacing_pct": spacing_pct,
                "levels": len(self._grid_levels) // 2
            })

        # Generate orders for unfilled levels near current price
        for level in self._grid_levels:
            if level.filled or level.order_id is not None:
                continue

            if level.side == "buy" and price <= level.price * 1.0005:
                actions.append({
                    "type": "place_order",
                    "side": "buy",
                    "price": level.price,
                    "quantity": level.quantity,
                    "level_price": level.price
                })
                level.order_id = f"buy_{level.price}_{timestamp}"
            elif level.side == "sell" and price >= level.price * 0.9995:
                actions.append({
                    "type": "place_order",
                    "side": "sell",
                    "price": level.price,
                    "quantity": level.quantity,
                    "level_price": level.price
                })
                level.order_id = f"sell_{level.price}_{timestamp}"

        return actions

    def on_fill(self, order_id: str, side: str, price: float, qty: float) -> None:
        """Handle fill: mark level filled, create opposite order."""
        for level in self._grid_levels:
            if level.order_id == order_id:
                level.filled = True
                level.order_id = None

                # Create opposite order at adjacent level
                idx = self._grid_levels.index(level)
                if side == "buy" and idx + 1 < len(self._grid_levels):
                    next_level = self._grid_levels[idx + 1]
                    if not next_level.filled and next_level.side == "sell":
                        next_level.order_id = f"sell_{next_level.price}_fill"
                elif side == "sell" and idx - 1 >= 0:
                    prev_level = self._grid_levels[idx - 1]
                    if not prev_level.filled and prev_level.side == "buy":
                        prev_level.order_id = f"buy_{prev_level.price}_fill"

                # Track PnL (simplified)
                fee = price * qty * self.config.fee_rate
                if side == "sell":
                    self._realized_pnl += price * qty - fee
                else:
                    self._realized_pnl -= price * qty + fee
                break

    def validate_config(self) -> bool:
        """Validate configuration."""
        try:
            self.config.validate()
            return True
        except ValueError:
            return False

    def estimate_memory_mb(self) -> float:
        """Estimate memory usage."""
        return self.config.estimate_memory_mb()

    def get_status(self) -> dict:
        """Return current strategy status for monitoring."""
        return {
            "center_price": self._center_price,
            "grid_levels": len(self._grid_levels),
            "filled_levels": sum(1 for l in self._grid_levels if l.filled),
            "total_deployed": self._total_deployed,
            "realized_pnl": self._realized_pnl,
            "current_spacing_pct": self._compute_dynamic_spacing(
                self._atr_values[-1] if self._atr_values else 0,
                self._center_price or 0
            ) if self._center_price else self.config.base_spacing_pct
        }


# Inline test with synthetic data
if __name__ == "__main__":
    import random

    print("=== AdaptiveGridStrategy Inline Test ===")

    config = AdaptiveGridConfig(
        symbol="DOGE/EUR",
        base_spacing_pct=0.005,
        levels=5,
        capital_per_level=5.0,
        volatility_window=20,
    )

    strat = AdaptiveGridStrategy(config)
    print(f"Config valid: {strat.validate_config()}")
    print(f"Estimated memory: {strat.estimate_memory_mb()} MB")

    # Generate synthetic price data with volatility regimes
    base_price = 0.15
    prices = []
    for i in range(100):
        regime = i // 25
        if regime == 0:
            vol = 0.005  # low vol
        elif regime == 1:
            vol = 0.02   # high vol
        elif regime == 2:
            vol = 0.008  # medium vol
        else:
            vol = 0.015  # high vol again

        change = random.gauss(0, vol)
        base_price *= (1 + change)
        prices.append(base_price)

    # Process ticks
    for i, price in enumerate(prices):
        actions = strat.on_tick(price, float(i))
        if actions:
            for a in actions:
                if a["type"] == "rebalance":
                    print(f"Tick {i}: REBALANCE - center={a['center_price']:.6f}, "
                          f"spacing={a['spacing_pct']:.4f}, levels={a['levels']}")

    status = strat.get_status()
    print(f"\nFinal Status:")
    print(f"  Center: {status['center_price']:.6f}")
    print(f"  Grid Levels: {status['grid_levels']}")
    print(f"  Filled: {status['filled_levels']}")
    print(f"  PnL: {status['realized_pnl']:.4f}")
    print(f"  Current Spacing: {status['current_spacing_pct']:.4f}")

    print("\n=== Test Passed ===")
