"""
Momentum-VWAP Anchored Adaptive Grid with Vol-Scaled Rebalance (MVA-AGR)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1).
Cycle 2026-08-29 20:15 UTC.

Improvement vs VTK-GAR (auto_gen_1788026645): VTK-GAR sizes by vol only.
MVA-AGR adds a rolling VWAP anchor so mean reversion targets the trade
volume weighted price (not just the last tick), and tilts grid spacing
asymmetric around the anchor when a short momentum impulse is detected.
OOM-safe: rolling VWAP via O(1) incremental sums, no history retention.

Ideas:
  1. VWAP anchor: incremental (sum_pv, sum_v) over N-tick window via a single
     fixed-size deque of (px, vol) slots. Anchor = sum_pv/sum_v.
  2. Momentum tilt: if fast-EWMA > slow-EWMA by > mom_band_pct, bias upward
     half denser (capture continuation); symmetric downward. Decays smoothly.
  3. Vol-scaled spacing rebalance: spacing = base_spacing_pct * vol_ratio,
     vol_ratio = clamp(vol_ewma/target_vol, floor, ceil). Levels rebuild only
     on anchor change -> bounds churn and trade count.
  4. Inventory band: when |inventory notional| > inv_band_pct * capital, fade
     the aggressor-side edge to force reversion.
  5. Drawdown gate: no new levels while dd > dd_gate with exponential cool.
"""
from __future__ import annotations

import gc
import math
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Dict, Optional, Tuple

DEFAULT_CONFIG: Dict[str, Any] = {
    "symbol": "SOL/EUR",
    "capital": 13.5,
    "vwap_window": 240,
    "mom_fast_span": 16,
    "mom_slow_span": 96,
    "mom_band_pct": 0.0015,
    "tilt_max": 0.6,
    "base_spacing_pct": 0.010,
    "target_vol": 0.012,
    "min_vol_floor": 0.004,
    "max_vol_ceil": 0.050,
    "vol_scale_power": 1.0,
    "max_levels": 9,
    "inv_band_pct": 0.35,
    "fee": 0.0016,
    "kelly_fraction": 0.30,
    "win_prob_assumed": 0.55,
    "dd_gate": 0.06,
    "dd_cool_base": 6,
    "stop_loss_frac": 0.12,
    "pending_cap": 20,
}
OPTIONAL_KEYS: Tuple[str, ...] = ()
MAX_PENDING_LEVELS = 20


def _ewma(prev: float, x: float, span: float, count: int) -> float:
    alpha = 2.0 / (span + 1.0)
    if count <= 0:
        return x
    return alpha * x + (1.0 - alpha) * prev


@dataclass
class EngineState:
    free_quote: float = 0.0
    total_equity: float = 0.0
    last_price: Optional[float] = None
    halt: bool = False
    regime: str = "neutral"
    levels: int = 0
    spacing: float = 0.0
    pending: Deque[float] = field(default_factory=deque)
    position_fills: int = 0
    realised_pnl: float = 0.0
    vwap_sum_pv: float = 0.0
    vwap_sum_v: float = 0.0
    vwap: Optional[float] = None
    vwap_slots: Deque[Tuple[float, float]] = field(default_factory=deque)
    mom_fast: Optional[float] = None
    mom_slow: Optional[float] = None
    vol_ewma: float = 0.0
    ewm_count: int = 0
    inventory_notional: float = 0.0
    equity_hwm: float = 0.0
    dd_active: bool = False
    cool_ticks_left: int = 0
    wins: int = 0
    losses: int = 0
    trades: int = 0
    ticks: int = 0


class StrategyBase:
    def on_tick(self, tick: Dict[str, Any]) -> Dict[str, Any]:
        raise NotImplementedError

    def on_fill(self, fill: Dict[str, Any]) -> Dict[str, Any]:
        raise NotImplementedError

    def validate_config(self, cfg: Dict[str, Any]) -> Tuple[bool, str]:
        raise NotImplementedError

    def estimate_memory_mb(self) -> float:
        raise NotImplementedError


class MVAAGRStrategy(StrategyBase):
    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        self.cfg: Dict[str, Any] = {**DEFAULT_CONFIG}
        if config:
            ok, err = self.validate_config(config)
            if not ok:
                raise ValueError(err)
            for k, v in config.items():
                if k not in OPTIONAL_KEYS:
                    self.cfg[k] = v
        self.state = EngineState()
        self._rebuild_gate: int = 0
        self._rebalance_anchor: Optional[float] = None

    def validate_config(self, cfg: Dict[str, Any]) -> Tuple[bool, str]:
        c = {**DEFAULT_CONFIG, **(cfg or {})}
        if not (2 <= c["mom_fast_span"] < c["mom_slow_span"]):
            return False, "mom_fast_span must be >=2 and < mom_slow_span"
        for pos in ("capital", "base_spacing_pct", "target_vol", "fee",
                    "dd_gate", "stop_loss_frac", "vwap_window"):
            if c.get(pos, 0) <= 0:
                return False, f"{pos} must be > 0"
        if not 0 < c["tilt_max"] <= 1:
            return False, "tilt_max in (0,1]"
        if not 0 < c["inv_band_pct"] <= 1:
            return False, "inv_band_pct in (0,1]"
        if not 1 <= c["max_levels"] <= MAX_PENDING_LEVELS:
            return False, f"max_levels in [1,{MAX_PENDING_LEVELS}]"
        return True, ""

    def estimate_memory_mb(self) -> float:
        slots = int(self.cfg["vwap_window"])
        slot_bytes = slots * 48.0
        return (slot_bytes + 64_000) / (1024 * 1024)

    def _clamp(self, x: float, lo: float, hi: float) -> float:
        return max(lo, min(hi, x))

    def _update_vwap(self, price: float, vol: float) -> None:
        w = int(self.cfg["vwap_window"])
        self.state.vwap_sum_pv += price * vol
        self.state.vwap_sum_v += vol
        self.state.vwap_slots.append((price, vol))
        if len(self.state.vwap_slots) > w:
            old_p, old_v = self.state.vwap_slots.popleft()
            self.state.vwap_sum_pv -= old_p * old_v
            self.state.vwap_sum_v -= old_v
        if self.state.vwap_sum_v > 0:
            self.state.vwap = self.state.vwap_sum_pv / self.state.vwap_sum_v

    def _update_ewma(self, price: float) -> None:
        s = self.state
        f = s.mom_fast if s.mom_fast is not None else price
        sl = s.mom_slow if s.mom_slow is not None else price
        s.mom_fast = _ewma(f, price, float(self.cfg["mom_fast_span"]), s.ewm_count)
        s.mom_slow = _ewma(sl, price, float(self.cfg["mom_slow_span"]), s.ewm_count)
        if s.last_price and s.last_price > 0:
            ret = abs(price - s.last_price) / s.last_price
            s.vol_ewma = _ewma(s.vol_ewma, ret, float(self.cfg["vwap_window"]), s.ewm_count)
        s.ewm_count += 1

    def _momentum_bias(self, price: float) -> float:
        s = self.state
        if s.mom_fast is None or s.mom_slow is None or s.mom_slow == 0:
            return 0.0
        delta = (s.mom_fast - s.mom_slow) / max(s.mom_slow, 1e-12)
        thr = float(self.cfg["mom_band_pct"])
        return self._clamp(delta / thr, -1.0, 1.0) if thr > 0 else 0.0

    def _inventory_penalty(self) -> float:
        s = self.state
        capital = float(self.cfg["capital"])
        if capital <= 0:
            return 1.0
        ratio = abs(s.inventory_notional) / capital
        band = float(self.cfg["inv_band_pct"])
        if ratio <= band:
            return 1.0
        over = (ratio - band) / band
        return self._clamp(1.0 - 0.5 * over, 0.5, 1.0)

    def on_tick(self, tick: Dict[str, Any]) -> Dict[str, Any]:
        s = self.state
        price = tick.get("price")
        vol = tick.get("volume", 0.0) or 0.0
        if price is None or price <= 0:
            return {"action": "none", "reason": "bad_price"}
        s.ticks += 1
        self._update_ewma(price)
        if vol > 0:
            self._update_vwap(price, vol)
        s.last_price = price
        eq = tick.get("equity") or (s.total_equity or 0.0)
        s.total_equity = float(eq)
        capital = float(self.cfg["capital"])

        if s.total_equity > s.equity_hwm:
            s.equity_hwm = s.total_equity
        if s.equity_hwm > 0:
            dd = (s.equity_hwm - s.total_equity) / s.equity_hwm
            if dd > float(self.cfg["dd_gate"]):
                s.dd_active = True
                s.cool_ticks_left = max(s.cool_ticks_left - 1, int(self.cfg["dd_cool_base"]))
            elif s.cool_ticks_left > 0:
                s.cool_ticks_left -= 1
            else:
                s.dd_active = False
        if s.dd_active or s.cool_ticks_left > 0:
            return {"action": "hold", "reason": "dd_gate", "cool_left": s.cool_ticks_left}

        vol_ratio = (s.vol_ewma / float(self.cfg["target_vol"])) if s.vol_ewma > 0 else 1.0
        vol_ratio = self._clamp(vol_ratio, float(self.cfg["min_vol_floor"]), float(self.cfg["max_vol_ceil"]))
        spacing = float(self.cfg["base_spacing_pct"]) * (vol_ratio ** float(self.cfg["vol_scale_power"]))
        s.spacing = spacing

        bias = self._momentum_bias(price)
        anchor = s.vwap if s.vwap is not None else price
        tilt_max = float(self.cfg["tilt_max"])
        up_share = self._clamp(0.5 + 0.5 * tilt_max * bias, 0.25, 0.75)
        s.regime = "bull" if bias > 0.3 else ("bear" if bias < -0.3 else "neutral")

        n_up = max(1, int(round(float(self.cfg["max_levels"]) * up_share)))
        n_down = max(1, int(round(float(self.cfg["max_levels"]) * (1.0 - up_share))))
        n_total = n_up + n_down

        if anchor != self._rebalance_anchor or (s.ticks - self._rebuild_gate) >= n_total:
            s.levels = n_total
            self._rebalance_anchor = anchor
            self._rebuild_gate = s.ticks
            gc.collect()

        return {"action": "rebalance", "anchor": anchor, "spacing": spacing,
                "levels_up": n_up, "levels_down": n_down,
                "penalty": self._inventory_penalty(), "regime": s.regime,
                "bias": bias, "vol_ratio": vol_ratio}

    def on_fill(self, fill: Dict[str, Any]) -> Dict[str, Any]:
        s = self.state
        side = fill.get("side")
        qty = float(fill.get("qty", 0.0))
        price = float(fill.get("price", 0.0))
        fee = float(fill.get("fee", 0.0)) or (qty * price * float(self.cfg["fee"]))
        s.position_fills += 1
        s.trades += 1
        s.pending.append(price)
        if len(s.pending) > int(self.cfg["pending_cap"]):
            s.pending.popleft()
        if side == "buy":
            s.inventory_notional += qty * price
        elif side == "sell":
            s.inventory_notional -= qty * price
        s.realised_pnl -= fee
        s.total_equity = max(0.0, s.total_equity - fee)
        pnl = float(fill.get("pnl", 0.0)) or 0.0
        if pnl > 0:
            s.wins += 1
        elif pnl < 0:
            s.losses += 1
        s.realised_pnl += pnl
        if float(self.cfg["capital"]) > 0 and s.realised_pnl <= -float(self.cfg["stop_loss_frac"]) * float(self.cfg["capital"]):
            s.halt = True
            return {"action": "halt", "reason": "stop_loss", "pnl": s.realised_pnl}
        return {"action": "ack", "side": side, "inventory_notional": s.inventory_notional,
                "pnl": s.realised_pnl, "halt": s.halt}


def _run_self_test() -> None:
    strat = MVAAGRStrategy()
    ok, err = strat.validate_config(DEFAULT_CONFIG)
    assert ok, err
    mem = strat.estimate_memory_mb()
    assert 0 < mem < 10, f"mem out of bounds: {mem}"
    px = 1.0
    for i in range(500):
        step = 0.004 if i % 2 == 0 else -0.001
        px = max(0.01, px * (1.0 + step))
        vol = 100.0 + (i % 7) * 10.0
        strat.on_tick({"price": px, "volume": vol, "equity": strat.state.total_equity or 13.5})
    assert strat.state.ticks == 500
    assert strat.state.vol_ewma > 0
    assert strat.state.vwap is not None
    assert strat.state.mom_fast is not None and strat.state.mom_slow is not None
    strat.on_fill({"side": "buy", "qty": 0.5, "price": px, "pnl": 0.001, "fee": 0.0002})
    strat.on_fill({"side": "sell", "qty": 0.5, "price": px * 1.01, "pnl": 0.004, "fee": 0.0002})
    assert strat.state.trades == 2
    assert strat.state.inventory_notional <= 1e-9
    assert strat.state.realised_pnl > 0.003
    print(f"[self-test] OK t={strat.state.ticks} mem~{mem:.3f}MB pnl={strat.state.realised_pnl:.4f} vol={strat.state.vol_ewma:.5f}")


if __name__ == "__main__":
    _run_self_test()
