"""VolRegimeGrid — adaptive grid with volatility-regime detection (generated by Hermes orchestration).

Angolo rispetto alle strategie precedenti (liqskewgrid, momrot, kellygrid, bsmgrid,
volregime, asrgrid, volavggrid): determina il regime di volatilità con EWMA su returns
(log-returns approssimati) e adatta SPACING dinamico per livelli, evitando l'allocazione
doppiamente conteggiata dei capitale e ricostruendo la griglia al cambio regime.
"""

from __future__ import annotations

import gc
import math
from collections import deque
from dataclasses import dataclass, field
from typing import Deque, Dict, List, Optional, Tuple

import numpy as np  # type: ignore


@dataclass
class VolRegimeGridConfig:
    """Configurazione verificata di VolRegimeGrid."""

    symbol: str = "SOL/EUR"
    capital: float = 13.5
    base_levels: int = 8
    level_alloc: float = 0.08                 # frazione capitale per livello
    max_total_levels: int = 14
    ewma_span: int = 90   # 90 dampens vol regime flips (DS fix)                        # span per EWMA returns
    atr_period: int = 20
    vol_low_q: float = 0.35
    vol_high_q: float = 0.65
    min_spacing_pct: float = 0.005
    max_spacing_pct: float = 0.03
    grid_rebuild_cooldown: int = 60            # tick tra rebuild per regime
    max_tick_buf: int = 200                    # deque dimensionata (no OOM)
    fee_pct: float = 0.0016

    def validate(self) -> List[str]:
        errors: List[str] = []
        if self.base_levels < 1:
            errors.append("base_levels must be >= 1")
        if self.level_alloc * self.base_levels > 1.0:
            errors.append("level_alloc * base_levels > 1.0 (capital over-commit)")
        if not (0 < self.min_spacing_pct < self.max_spacing_pct):
            errors.append("spacing must satisfy 0 < min < max")
        if self.max_total_levels < self.base_levels:
            errors.append("max_total_levels < base_levels")
        return errors


class VolRegimeGrid:
    """Griglia adattiva con regime di volatilità.

    Design:
      - log-return EWMA per stimare volatilità corrente
      - spacing = clip(vol_factor, min, max); expande la griglia in regime alto,
        la stringe in regime basso (cattura range small, evita over-trading).
      - allocazione capitale esplicita e mai doppia (level_alloc * base_levels <= 1).
      - streaming: deque dimensionata, nessuna list comprehension su serie intere.
    """

    def __init__(self, config: VolRegimeGridConfig) -> None:
        errs = config.validate()
        if errs:
            raise ValueError("; ".join(errs))
        self.cfg = config
        self.prices: Deque[float] = deque(maxlen=config.max_tick_buf)
        self.ret_ewma: Optional[float] = None
        self.base_price: Optional[float] = None
        self.spacing_pct: float = config.min_spacing_pct
        self.levels: List[float] = []
        self.positions: Dict[float, float] = {}
        self.tick_count: int = 0
        self.last_rebuild_tick: int = 0
        self.pnl: float = 0.0
        self.trades: int = 0

    # -- internals -----------------------------------------------------------
    def _ewma_return(self, price: float) -> float:
        if self.prices:
            prev = self.prices[-1]
            if prev > 0:
                r = math.log(price / prev)
                alpha = 2.0 / (self.cfg.ewma_span + 1.0)
                self.ret_ewma = r if self.ret_ewma is None else alpha * r + (1.0 - alpha) * self.ret_ewma
        self.prices.append(price)
        return self.ret_ewma or 0.0

    def _vol_factor(self) -> float:
        if not self.prices:
            return 0.5
        vol = abs(self._ewma_return(self.prices[-1]))
        lo, hi = self.cfg.vol_low_q, self.cfg.vol_high_q
        if vol <= 0:
            return 0.5
        if vol <= lo:
            return 0.35 + (vol / lo) * 0.30
        if vol <= hi:
            return 0.65 + ((vol - lo) / (hi - lo)) * 0.30
        return 1.0

    def _rebuild(self, price: float) -> None:
        self.spacing_pct = float(
            np.clip(
                self.cfg.min_spacing_pct * (0.5 + self._vol_factor()),
                self.cfg.min_spacing_pct,
                self.cfg.max_spacing_pct,
            )
        )
        n = min(self.cfg.base_levels, self.cfg.max_total_levels)
        self.levels = [round(price * (1.0 - self.spacing_pct * (i + 1)), 6) for i in range(n)]
        self.last_rebuild_tick = self.tick_count

    # -- public API ----------------------------------------------------------
    def on_tick(self, price: float) -> List[Tuple[float, float, float]]:
        """Returna segnali [(side, price, size)]; side: +1 buy / -1 sell."""
        self.tick_count += 1
        if not self.prices:
            self.prices.append(price)
            self.base_price = price
            self._rebuild(price)
            return []
        vol_change = abs(self._vol_factor() - 0.65) >= 0.40
        if self.tick_count - self.last_rebuild_tick > self.cfg.grid_rebuild_cooldown and vol_change:
            self._rebuild(price)
            self.base_price = price
        signals: List[Tuple[float, float, float]] = []
        for lvl in self.levels:
            if lvl not in self.positions and price <= lvl:
                size = self.cfg.capital * self.cfg.level_alloc / lvl
                self.positions[lvl] = size
                signals.append((+1.0, lvl, size))
        return signals

    def on_fill(self, price: float, side: float, size: float) -> Optional[float]:
        """Registra fill; returna PnL se è un take-profit (side<0)."""
        if side > 0:
            return None
        best, best_key = 1e18, None
        for k, _ in self.positions.items():
            if abs(k - price) < abs(best - price):
                best, best_key = k, k
        if best_key is None:
            return None
        entry = self.positions.pop(best_key, 0.0)
        if entry <= 0:
            return None
        pnl = ((price - best) * size) - (price * size * self.cfg.fee_pct) * 2
        self.pnl += pnl
        self.trades += 1
        return pnl

    def estimate_memory_mb(self) -> float:
        """Stima piccola (streaming): deque + poche liste di livello."""
        return (self.cfg.max_tick_buf * 16.0 + len(self.levels) * 64.0) / (1024.0 * 1024.0)

    def describe(self) -> Dict[str, object]:
        return {
            "symbol": self.cfg.symbol,
            "spacing_pct": round(self.spacing_pct, 5),
            "levels": len(self.levels),
            "positions": len(self.positions),
            "pnl": round(self.pnl, 6),
            "trades": self.trades,
            "mem_mb": round(self.estimate_memory_mb(), 4),
        }


if __name__ == "__main__":
    # Smoke test con dati sintetici piccoli
    cfg = VolRegimeGridConfig(capital=13.5)
    s = VolRegimeGrid(cfg)
    px = 1.0
    n = 0
    for i in range(300):
        px = px * (1.0 + (0.001 if i % 2 == 0 else -0.0015))
        sigs = s.on_tick(px)
        for side, p, size in sigs:
            s.on_fill(p, side, size)
        if i % 3 == 0 and s.positions:
            k = next(iter(s.positions))
            s.on_fill(k + 0.002, -1.0, s.positions[k])
        n += len(sigs)
    assert s.trades >= 0
    print("smoke OK: ticks=300 signals=", n, "pnl=", round(s.pnl, 6), "mem_mb=", s.estimate_memory_mb())
    gc.collect()
