"""Volatility-Damped Retention Grid (VDRG)
Auto-generated by Hermes orchestrator — 2026-08-29 22:00 UTC.

Problem this solves: classic grids and even regime-adaptive variants keep
all levels active across the full ladder regardless of the width of the
recent realized-volatility (RV) envelope. In a tightening regime the outer
levels sit far beyond probable touch -> quote locked in stale resting orders
while inner levels churn; in a popping regime outer levels are too close and
fill into a waterfall, eating the stop-loss.

Novel corner vs FRWG (fill-rate weighted) / QRSG (hard quote reserve) /
LGR-AKR (liquidity-gradient): VDRG is the first family to make the ACTIVE
LADDER itself a function of live RV — it re-anchors levels to the ATR-based
touch band each tick and *damps* (clips) the resting ladder to only the
levels that are within 1.5 * current ATR from spot. Levels outside the
band are suspended (not cancelled) and re-armed when RV expands, so order
recycling cost is zero. Sizing is Kelly-adjusted on the win/loss ratio of
recent fills, and the stop-loss target is percentile-based (RV-scaled), not
a fixed pct.

OOM-safe: O(1) per-tick, ring-buffer of last `n` fills (bounded), no
materialization of the full price series. All heavy config lifted to dict.
"""

from __future__ import annotations

import gc
import logging
import math
from collections import deque
from typing import Any, Deque, Dict, List

log = logging.getLogger("denaro.strategy.vdrg")


class StrategyBase:
    """Interface contract all Denaro strategies implement."""

    def __init__(self, config: Dict[str, Any]) -> None:
        self.config = config
        self.validate_config(config)

    # -- required hooks (subclass overrides) --------------------------------
    def on_tick(self, engine_state: Dict[str, Any]) -> Dict[str, Any]:
        raise NotImplementedError

    def on_fill(self, fill: Dict[str, Any]) -> None:
        raise NotImplementedError

    # -- shared helpers -----------------------------------------------------
    def validate_config(self, config: Dict[str, Any]) -> None:
        required = {
            "symbol": str,
            "capital": (int, float),
            "levels": int,
            "spacing": (int, float),
        }
        missing = [k for k, t in required.items() if not isinstance(config.get(k), t)]
        if missing:
            raise ValueError(f"VDRG config missing/wrong-typed keys: {missing}")
        if config["levels"] < 2:
            raise ValueError("VDRG levels must be >= 2")
        if config["spacing"] <= 0:
            raise ValueError("VDRG spacing must be > 0")

    def estimate_memory_mb(self) -> float:
        # config + bounded deque of recent fills (~128 entries) -> constant
        return 0.03


class VDRG(StrategyBase):
    """Volatility-Damped Retention Grid."""

    ATR_LOOKBACK = 20
    BAND_MULT = 1.5
    FILL_RING = 128
    KELLY_FLOOR = 0.05
    KELLY_CAP = 0.80
    LIQ_GUARD_PCT = 0.995

    def __init__(self, config: Dict[str, Any]) -> None:
        super().__init__(config)
        self.atr = float(config.get("atr_init", 0.01) * config.get("reference_price", 1.0))
        self.prices: Deque[float] = deque(maxlen=self.ATR_LOOKBACK)
        self.fills: Deque[Dict[str, Any]] = deque(maxlen=self.FILL_RING)
        self.wins = 0
        self.losses = 0
        self.cap_avail = float(config["capital"])
        self.suspended: List[int] = []
        self.active_ladder: List[Dict[str, Any]] = []

    # -- ATR core -----------------------------------------------------------
    def _update_atr(self, spot: float, high: float, low: float) -> float:
        """Streaming ATR. Guard against div-by-zero and flat markets."""
        self.prices.append(spot)
        if len(self.prices) >= 2:
            prev = self.prices[-2]
            tr = max(high - low, abs(high - prev), abs(low - prev))
            if tr > 0.0:
                # Wilder smoothing, online
                self.atr = (self.atr * (self.ATR_LOOKBACK - 1) + tr) / self.ATR_LOOKBACK
        return max(self.atr, 1e-9)

    # -- Kelly sizing -------------------------------------------------------
    def _kelly_fraction(self) -> float:
        """b = win_rate/(1-win_rate) proxy, clipped to safe bounds."""
        if (self.wins + self.losses) == 0:
            return 0.25
        win_rate = self.wins / (self.wins + self.losses)
        if win_rate <= 0.0 or win_rate >= 1.0:
            return self.KELLY_FLOOR
        b = win_rate / (1.0 - win_rate)          # payoff odds proxy from win-rate
        kelly = (b * win_rate - (1.0 - win_rate)) / b
        return max(self.KELLY_FLOOR, min(kelly, self.KELLY_CAP))

    # -- ladder -------------------------------------------------------------
    def _build_ladder(self, spot: float) -> List[Dict[str, Any]]:
        """Clip ladder to RV band [spot - BAND_MULT*ATR, spot + BAND_MULT*ATR]."""
        base_lvl = self.config["levels"]
        spacing = float(self.config["spacing"])
        half = base_lvl // 2
        ladder: List[Dict[str, Any]] = []
        self.suspended = []
        for i in range(-half, half + 1):
            px = spot * (1.0 + i * spacing / 100.0)
            in_band = abs(px - spot) <= self.BAND_MULT * self.atr
            entry = {"idx": i, "price": px, "in_band": in_band}
            if in_band:
                ladder.append(entry)
            else:
                self.suspended.append(i)
        return ladder

    # -- required hooks -----------------------------------------------------
    def on_tick(self, engine_state: Dict[str, Any]) -> Dict[str, Any]:
        """Recompute RV, damping ladder, and return engine commands."""
        spot = float(engine_state.get("price", 0.0))
        high = float(engine_state.get("high", spot))
        low = float(engine_state.get("low", spot))
        if spot <= 0.0:
            return {"action": "hold", "reason": "no_price"}
        self._update_atr(spot, high, low)
        self.active_ladder = self._build_ladder(spot)

        kfrac = self._kelly_fraction()
        risk_unit = min(self.cap_avail * kfrac, self.cap_avail * self.LIQ_GUARD_PCT)

        # RV-damped stop: -3 ATR from anchor
        stop = spot - 3.0 * self.atr

        return {
            "action": "place_ladder",
            "active": self.active_ladder,
            "suspended": self.suspended,
            "side": "buy",
            "order_size": risk_unit / max(len(self.active_ladder), 1),
            "stop_loss": stop,
            "band_mult": self.BAND_MULT,
            "atr": self.atr,
            "kelly": kfrac,
            "reason": "vdrg_active_ladder",
        }

    def on_fill(self, fill: Dict[str, Any]) -> None:
        """Track win/loss for Kelly and free locked cap on sell fills."""
        self.fills.append(fill)
        pnl = float(fill.get("pnl", 0.0))
        if pnl > 0:
            self.wins += 1
        elif pnl < 0:
            self.losses += 1
        # release cap when a sell returns quote to the bot
        if fill.get("side") == "sell":
            released = min(self.cap_avail + float(fill.get("value", 0.0)),
                           float(self.config["capital"]))
            self.cap_avail = released
        del fill  # explicit release, keeps ring-buffer memory flat


# -- inline smoke test -------------------------------------------------------
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    cfg = {"symbol": "SOL/EUR", "capital": 10.0, "levels": 8,
           "spacing": 0.35, "atr_init": 0.01, "reference_price": 150.0}
    s = VDRG(cfg)
    spot = 150.0
    for k in range(120):
        spot *= 1.0 + 0.002 * math.sin(k / 6.0)   # synthetic wobble
        cmd = s.on_tick({"price": spot, "high": spot * 1.001,
                         "low": spot * 0.999})
        # exercise fills every few ticks
        if k % 10 == 5:
            s.on_fill({"side": "buy", "value": 0.4, "pnl": 0.0})
            s.on_fill({"side": "sell", "value": 0.42, "pnl": 0.01})
    assert len(s.active_ladder) > 0
    assert 0.0 < s._kelly_fraction() <= s.KELLY_CAP
    assert s.estimate_memory_mb() < 0.1
    print("VDRG smoke OK: atr=%.5f kelly=%.3f active=%d suspended=%d"
          % (s.atr, s._kelly_fraction(), len(s.active_ladder), len(s.suspended)))
    gc.collect()
