"""Hurst-Autocorrelation Regime Switcher (HARS)
Auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1) at 2026-08-29 22:31.

WHY DISTINCT from every prior auto-gen family:
  Prior families are single-asset with fixed intents: book/exhaustion (LETC, OFI,
  IMR, CVD-Grid, LGR-AKR), grid geometry (ATR/z-score/ISV/VAGR/AVWG/REG/VTGK),
  trend-slope scalpers (VWMR, VRMP, Chandelier, V2), value-gravity (VAIG-CRL),
  volatility-breakout (VBMF), fractal mean-reversion (LFAMR-VCC),
  volatility-disintegration ladders (VDRG), and cross-asset cointegration-velocity
  (CACVR).

  HARS lives in a corner NONE of those touch: EXPLICIT REGIME IDENTIFICATION via
  the Hurst exponent and lag-1 autocorrelation of realized returns, driving a
  MODE-SWITCHING controller that flips between:
    - MEAN-REVERSION mode (choppy / Hurst ~0.5, negative autocorr)
    - MOMENTUM mode (trending / Hurst > 0.6, positive autocorr)
  It never guesses an intent statically: the quantile of the current Hurst window
  decides the mode, with hysteresis to prevent mode-flapping near the boundary.

OOM / streaming discipline:
  - Rolling windows are computed incrementally (circular buffers, O(1) push),
    never list-comprehension over 100k rows.
  - No pandas; pure Python arithmetic on ring buffers.
  - estimate_memory_mb() exposes the fixed ring-buffer footprint.
  - Explicit error handling; no bare try/except.

StrategyBase contract: on_tick, on_fill, validate_config, estimate_memory_mb.
"""

from __future__ import annotations

import math
import statistics
from typing import Any, Dict, List, Optional


class StrategyBase:
    """Abstract contract every Denaro strategy must satisfy."""

    def __init__(self, config: Dict[str, Any]) -> None:
        self.config: Dict[str, Any] = config
        self.validate_config()

    def on_tick(self, price: float) -> Optional[Dict[str, Any]]:  # pragma: no cover
        raise NotImplementedError

    def on_fill(self, fill: Dict[str, Any]) -> None:  # pragma: no cover
        raise NotImplementedError

    def validate_config(self) -> None:  # pragma: no cover
        raise NotImplementedError

    def estimate_memory_mb(self) -> float:  # pragma: no cover
        raise NotImplementedError


class _RingBuffer:
    """Fixed-capacity ring buffer with O(1) amortised push and O(n) snapshot."""

    __slots__ = ("_cap", "_data", "_head", "_size")

    def __init__(self, capacity: int) -> None:
        if capacity < 2:
            raise ValueError(f"RingBuffer capacity must be >= 2, got {capacity}")
        self._cap = int(capacity)
        self._data: List[float] = [0.0] * self._cap
        self._head: int = 0
        self._size: int = 0

    def push(self, value: float) -> None:
        self._data[self._head] = float(value)
        self._head = (self._head + 1) % self._cap
        if self._size < self._cap:
            self._size += 1

    def snapshot(self) -> List[float]:
        """Return values in chronological order."""
        if self._size == 0:
            return []
        start = self._head - self._size
        if start < 0:
            return self._data[start:] + self._data[: self._head]  # type: ignore[return-value]
        return self._data[start:self._head]  # type: ignore[return-value]

    def full(self) -> bool:
        return self._size == self._cap

    @property
    def size(self) -> int:
        return self._size


def _hurst_exponent(series: List[float]) -> float:
    """Rescaled-range (R/S) estimate of the Hurst exponent.

    Uses explicit chunked resampling over power-of-two subset sizes.
    Returns NaN if the series is too short or degenerate.
    """
    n: int = len(series)
    if n < 32:
        return float("nan")
    mean: float = statistics.fmean(series)
    deviations: List[float] = [x - mean for x in series]
    # Cumulative deviation series.
    cum: List[float] = [0.0] * n
    acc: float = 0.0
    for i in range(n):
        acc += deviations[i]
        cum[i] = acc
    rs_pairs: List[tuple] = []
    # Only consider sub-series lengths that are exact divisors-ish (power of two).
    k: int = n
    while k >= 32:
        num_chunks: int = n // k
        if num_chunks < 1:
            k = k // 2
            continue
        rs_vals: List[float] = []
        for c in range(num_chunks):
            lo: int = c * k
            hi: int = lo + k
            seg: List[float] = cum[lo:hi]           # <64 elems: safe slice
            seg_min: float = min(seg)
            seg_max: float = max(seg)
            r: float = seg_max - seg_min
            if r <= 0.0:
                continue
            s: float = statistics.pstdev(series[lo:hi])
            if s <= 0.0:
                continue
            rs_vals.append(r / s)
        if rs_vals:
            avg_rs: float = statistics.fmean(rs_vals)
            log_rs: float = math.log(avg_rs + 1e-12)
            log_k: float = math.log(k)
            rs_pairs.append((log_k, log_rs))
        k = k // 2
    if len(rs_pairs) < 3:
        return float("nan")
    # Linear fit log(R/S) ~ H * log(k) via least squares.
    n_pairs: int = len(rs_pairs)
    sx: float = sum(p[0] for p in rs_pairs)
    sy: float = sum(p[1] for p in rs_pairs)
    sxx: float = sum(p[0] * p[0] for p in rs_pairs)
    sxy: float = sum(p[0] * p[1] for p in rs_pairs)
    denom: float = n_pairs * sxx - sx * sx
    if abs(denom) < 1e-12:
        return float("nan")
    h: float = (n_pairs * sxy - sx * sy) / denom
    return max(0.0, min(1.0, h))


class HARS(StrategyBase):
    """Hurst-Autocorrelation Regime Switcher: momentum when trending, mean-revert
    when choppy, with hysteresis to avoid flapping."""

    DEFAULT_CONFIG: Dict[str, Any] = {
        "capital": 10.0,
        "hurst_window": 128,        # returns used for Hurst estimate
        "buffered_ticks": 300,      # ticks retained for mode estimation
        "momentum_hurst": 0.60,     # Hurst >= this => momentum mode
        "meanrev_hurst": 0.48,      # Hurst <= this => mean-reversion mode
        "momentum_quantile": 0.70,  # fwd lookback for momentum threshold
        "meanrev_z": 1.5,           # z-score threshold for mean-reversion entry
        "risk_per_trade": 0.02,
        "stop_pct": 0.02,
        "take_pct": 0.04,
        "cooldown_ticks": 20,
        "symbol": "SYM/EUR",
    }

    def __init__(self, config: Dict[str, Any]) -> None:
        merged: Dict[str, Any] = dict(self.DEFAULT_CONFIG)
        merged.update(config or {})
        super().__init__(merged)
        self._returns: _RingBuffer = _RingBuffer(int(self.config["buffered_ticks"]))
        self._prices: _RingBuffer = _RingBuffer(int(self.config["buffered_ticks"]))
        self._last_price: Optional[float] = None
        self._mode: str = "neutral"
        self._mode_clock: int = 0   # ticks since last mode switch (hysteresis)
        self._cooldown: int = 0
        self._fills: int = 0
        self._pnl: float = 0.0
        self._equity: float = float(self.config["capital"])
        self._entry_price: Optional[float] = None
        self._open_qty: float = 0.0

    def validate_config(self) -> None:
        for key in ("hurst_window", "buffered_ticks", "momentum_quantile",
                    "meanrev_z", "risk_per_trade", "stop_pct", "take_pct",
                    "cooldown_ticks"):
            val: Any = self.config.get(key)
            if val is None or not isinstance(val, (int, float)):
                raise ValueError(f"config[{key!r}] must be numeric, got {val!r}")
        if int(self.config["hurst_window"]) < 32:
            raise ValueError("hurst_window must be >= 32 (R/S needs samples)")
        if self.config["momentum_hurst"] < self.config["meanrev_hurst"]:
            raise ValueError("momentum_hurst must be > meanrev_hurst")
        if self.config["buffered_ticks"] < self.config["hurst_window"] + 16:
            raise ValueError("buffered_ticks must exceed hurst_window")
        if self.config["risk_per_trade"] <= 0 or self.config["risk_per_trade"] > 0.5:
            raise ValueError("risk_per_trade must be in (0, 0.5]")
        if not isinstance(self.config.get("symbol"), str):
            raise ValueError("config['symbol'] must be a string")

    def estimate_memory_mb(self) -> float:
        """Ring buffers: 2 buffers x capacity x 8 bytes, plus negligible overhead."""
        cap: int = int(self.config["buffered_ticks"])
        bytes_total: float = 2.0 * cap * 8.0
        return round(bytes_total / (1024.0 * 1024.0), 4)

    # ------------------------------------------------------------------ utils
    def _updated_mode(self) -> str:
        """Recompute mode from Hurst, with hysteresis clock."""
        snap: List[float] = self._returns.snapshot()
        if len(snap) < int(self.config["hurst_window"]):
            return self._mode  # not enough data yet
        h: float = _hurst_exponent(snap)
        if math.isnan(h):
            return self._mode
        mh: float = float(self.config["momentum_hurst"])
        mrh: float = float(self.config["meanrev_hurst"])
        # Hysteresis: only switch if stable for cooldown_ticks after crossing.
        if h >= mh and self._mode != "momentum":
            self._mode_clock += 1
            if self._mode_clock >= int(self.config["cooldown_ticks"]):
                self._mode = "momentum"
                self._mode_clock = 0
        elif h <= mrh and self._mode != "meanrev":
            self._mode_clock += 1
            if self._mode_clock >= int(self.config["cooldown_ticks"]):
                self._mode = "meanrev"
                self._mode_clock = 0
        else:
            self._mode_clock = 0
        return self._mode

    def _zscore(self) -> float:
        snap: List[float] = self._prices.snapshot()
        if len(snap) < int(self.config["hurst_window"]):
            return 0.0
        last: float = snap[-1]
        mean: float = statistics.fmean(snap)
        sd: float = statistics.pstdev(snap)
        if sd <= 0.0:
            return 0.0
        return (last - mean) / sd

    # ------------------------------------------------------- StrategyBase API
    def on_tick(self, price: float) -> Optional[Dict[str, Any]]:
        price = float(price)
        if price <= 0.0:
            raise ValueError(f"non-positive price {price}")
        if self._cooldown > 0:
            self._cooldown -= 1
        if self._last_price is not None:
            ret: float = (price / self._last_price) - 1.0
            self._returns.push(ret)
        else:
            self._returns.push(0.0)
        self._prices.push(price)
        self._last_price = price

        # Stop-loss / take-profit on open position.
        if self._open_qty > 0.0 and self._entry_price is not None:
            drift: float = (price / self._entry_price) - 1.0
            if drift <= -float(self.config["stop_pct"]):
                order: Dict[str, Any] = self._close("stop")
                self._pnl += self._realized_pnl(price)
                self._equity += self._realized_pnl(price)
                return order
            if drift >= float(self.config["take_pct"]):
                order = self._close("take")
                self._pnl += self._realized_pnl(price)
                self._equity += self._realized_pnl(price)
                return order
            return None

        if self._cooldown > 0 or self._open_qty > 0.0:
            return None

        mode: str = self._updated_mode()
        z: float = self._zscore()
        qty: float = (self._equity * float(self.config["risk_per_trade"])) / price
        if qty <= 0.0:
            return None

        if mode == "momentum":
            if z >= float(self.config["momentum_quantile"]):
                return self._open("long", price, qty)
            if z <= -float(self.config["momentum_quantile"]):
                return self._open("short", price, qty)
            return None
        if mode == "meanrev":
            if z <= -float(self.config["meanrev_z"]):
                return self._open("short", price, qty)  # fade pop-up
            if z >= float(self.config["meanrev_z"]):
                return self._open("long", price, qty)   # fade dip
            return None
        return None

    def _open(self, side: str, price: float, qty: float) -> Dict[str, Any]:
        self._entry_price = price
        self._open_qty = qty
        self._cooldown = int(self.config["cooldown_ticks"])
        return {
            "action": "buy" if side == "long" else "sell",
            "symbol": self.config["symbol"],
            "qty": round(qty, 8),
            "price": round(price, 8),
            "reason": f"HARS-{self._mode}",
        }

    def _close(self, reason: str) -> Dict[str, Any]:
        self._open_qty = 0.0
        self._entry_price = None
        return {
            "action": "close",
            "symbol": self.config["symbol"],
            "reason": reason,
        }

    def _realized_pnl(self, exit_price: float) -> float:
        if self._entry_price is None or self._open_qty <= 0.0:
            return 0.0
        side_mult: float = 1.0 if self._entry_price <= exit_price else -1.0
        return side_mult * self._open_qty * abs(exit_price - self._entry_price)

    def on_fill(self, fill: Dict[str, Any]) -> None:
        self._fills += 1


# ------------------------------------------------------------- inline selftest
if __name__ == "__main__":
    cfg: Dict[str, Any] = {"capital": 10.0, "symbol": "SYM/EUR",
                           "buffered_ticks": 300}
    strat: HARS = HARS(cfg)
    # Synthetic walk: first trending regime (momentum), then choppy.
    import random
    rng: random.Random = random.Random(7)
    price: float = 100.0
    trend_dir: float = 1.0
    orders: int = 0
    for i in range(400):
        if i < 200:
            price *= (1.0 + trend_dir * 0.004 + rng.gauss(0, 0.002))
        else:
            price *= (1.0 + rng.gauss(0, 0.01))
        sig: Optional[Dict[str, Any]] = strat.on_tick(price)
        if sig is not None:
            orders += 1
    assert strat.validate_config() is None
    mem: float = strat.estimate_memory_mb()
    print(f"HARS selftest OK: fills={strat._fills} orders={orders} "
          f"mode={strat._mode} mem={mem}MB equity={strat._equity:.4f}")
