"""
Adaptive Grid-Momentum Strategy
Auto-generated by Hermes orchestrator.
Combines grid trading with momentum filtering and adaptive spacing.
"""

from __future__ import annotations

import gc
import math
import sys
from dataclasses import dataclass
from typing import Any, Generator, Iterator, Protocol

import numpy as np


class MarketData(Protocol):
    """Protocol for market data feed."""

    def get_price(self) -> float: ...
    def get_volume(self) -> float: ...
    def get_timestamp(self) -> int: ...


class OrderManager(Protocol):
    """Protocol for order management."""

    def place_limit(self, side: str, price: float, size: float) -> str: ...
    def place_market(self, side: str, size: float) -> str: ...
    def cancel(self, order_id: str) -> bool: ...
    def get_open_orders(self) -> list[dict[str, Any]]: ...


@dataclass(frozen=True, slots=True)
class GridConfig:
    """Configuration for adaptive grid strategy."""
    symbol: str
    base_spacing_pct: float = 0.005
    max_levels: int = 20
    capital_per_grid: float = 10.0
    momentum_window: int = 50
    momentum_threshold: float = 0.002
    volatility_window: int = 100
    min_spacing_pct: float = 0.002
    max_spacing_pct: float = 0.02
    rebalance_interval: int = 300
    stop_loss_pct: float = 0.05
    take_profit_pct: float = 0.03
    chunk_size: int = 1000

    def validate(self) -> None:
        """Validate configuration parameters."""
        if not self.symbol:
            raise ValueError("symbol required")
        if not 0 < self.base_spacing_pct <= 1:
            raise ValueError("base_spacing_pct must be in (0, 1]")
        if self.max_levels <= 0:
            raise ValueError("max_levels must be positive")
        if self.capital_per_grid <= 0:
            raise ValueError("capital_per_grid must be positive")
        if self.momentum_window <= 0:
            raise ValueError("momentum_window must be positive")
        if not 0 <= self.momentum_threshold < 1:
            raise ValueError("momentum_threshold must be in [0, 1)")
        if self.volatility_window <= 0:
            raise ValueError("volatility_window must be positive")
        if not 0 < self.min_spacing_pct <= self.max_spacing_pct <= 1:
            raise ValueError("invalid spacing bounds")
        if self.rebalance_interval <= 0:
            raise ValueError("rebalance_interval must be positive")
        if not 0 < self.stop_loss_pct < 1:
            raise ValueError("stop_loss_pct must be in (0, 1)")
        if not 0 < self.take_profit_pct < 1:
            raise ValueError("take_profit_pct must be in (0, 1)")
        if self.chunk_size <= 0:
            raise ValueError("chunk_size must be positive")


@dataclass(slots=True)
class GridLevel:
    """Single grid level state."""
    price: float
    side: str
    size: float
    order_id: str | None = None
    filled: bool = False


class StrategyBase:
    """
    Base class for all trading strategies.
    Defines the required interface.
    """

    def on_tick(self, market: MarketData, orders: OrderManager) -> None:
        """Process a market tick."""
        raise NotImplementedError

    def on_fill(self, order_id: str, side: str, price: float, size: float) -> None:
        """Handle order fill event."""
        raise NotImplementedError

    def validate_config(self, config: dict[str, Any]) -> bool:
        """Validate strategy configuration."""
        raise NotImplementedError

    def estimate_memory_mb(self, config: dict[str, Any] | None = None) -> float:
        """Estimate memory usage in MB for given config."""
        raise NotImplementedError


class AdaptiveGridMomentum(StrategyBase):
    """
    Adaptive Grid Strategy with Momentum Filter.

    Features:
    - Dynamic grid spacing based on volatility
    - Momentum filter to avoid counter-trend grids
    - Streaming price processing (OOM-safe)
    - Explicit error handling
    - Config-driven, no hardcoded values
    """

    def __init__(self, config: GridConfig) -> None:
        config.validate()
        self.config = config
        self._price_history: list[float] = []
        self._volume_history: list[float] = []
        self._grid_levels: list[GridLevel] = []
        self._last_rebalance: int = 0
        self._position: float = 0.0
        self._entry_price: float = 0.0
        self._realized_pnl: float = 0.0

    def estimate_memory_mb(self, config: dict[str, Any] | None = None) -> float:
        """
        Estimate memory usage in MB.

        Args:
            config: Optional config override for estimation.

        Returns:
            Estimated memory in MB.
        """
        cfg = config or vars(self.config)
        price_hist = cfg.get("momentum_window", 50) + cfg.get("volatility_window", 100)
        grid_levels = cfg.get("max_levels", 20)
        # Rough estimate: 8 bytes per float, plus object overhead
        base_mb = (price_hist * 8 * 2 + grid_levels * 200) / (1024 * 1024)
        return max(base_mb, 0.5)

    def validate_config(self, config: dict[str, Any]) -> bool:
        """Validate strategy configuration dict."""
        try:
            GridConfig(**config).validate()
            return True
        except (ValueError, TypeError) as e:
            raise ValueError(f"Invalid config: {e}") from e

    def _stream_prices(self, market: MarketData) -> Generator[float, None, None]:
        """
        Stream prices from market data with chunking.
        OOM-safe: yields one price at a time.
        """
        while True:
            try:
                price = market.get_price()
                if price > 0:
                    yield price
            except AttributeError as e:
                raise RuntimeError(f"Market data missing required method: {e}") from e
            except Exception as e:
                raise RuntimeError(f"Failed to fetch price: {e}") from e

    def _update_momentum(self) -> float:
        """Calculate momentum from price history. Returns momentum ratio."""
        if len(self._price_history) < self.config.momentum_window:
            return 0.0
        window = self._price_history[-self.config.momentum_window:]
        if window[0] == 0:
            return 0.0
        return (window[-1] - window[0]) / window[0]

    def _update_volatility(self) -> float:
        """Calculate volatility (std of returns) from price history."""
        if len(self._price_history) < self.config.volatility_window:
            return self.config.base_spacing_pct
        window = self._price_history[-self.config.volatility_window:]
        returns = np.diff(window) / window[:-1]
        if len(returns) == 0:
            return self.config.base_spacing_pct
        vol = float(np.std(returns))
        # Scale spacing by volatility, clamp to bounds
        spacing = vol * 2.0
        return max(self.config.min_spacing_pct, min(self.config.max_spacing_pct, spacing))

    def _build_grid(self, mid_price: float, spacing_pct: float) -> list[GridLevel]:
        """Build grid levels around mid price."""
        levels = []
        half = self.config.max_levels // 2
        for i in range(-half, half + 1):
            if i == 0:
                continue
            level_price = mid_price * (1 + i * spacing_pct)
            side = "buy" if i < 0 else "sell"
            size = self.config.capital_per_grid / level_price
            levels.append(GridLevel(price=level_price, side=side, size=size))
        return levels

    def _place_grid_orders(self, orders: OrderManager, levels: list[GridLevel]) -> None:
        """Place limit orders for all grid levels."""
        for level in levels:
            if level.order_id is None and not level.filled:
                try:
                    order_id = orders.place_limit(level.side, level.price, level.size)
                    level.order_id = order_id
                except Exception as e:
                    # Log and continue - don't fail entire grid
                    print(f"[ERROR] Failed to place {level.side} at {level.price}: {e}", file=sys.stderr)

    def _check_rebalance(self, timestamp: int, market: MarketData) -> bool:
        """Check if grid rebalance is needed."""
        if timestamp - self._last_rebalance >= self.config.rebalance_interval:
            return True
        momentum = abs(self._update_momentum())
        if momentum > self.config.momentum_threshold * 5:
            return True
        return False

    def _cancel_all_orders(self, orders: OrderManager) -> None:
        """Cancel all open orders."""
        for level in self._grid_levels:
            if level.order_id:
                try:
                    orders.cancel(level.order_id)
                    level.order_id = None
                except Exception as e:
                    print(f"[ERROR] Failed to cancel {level.order_id}: {e}", file=sys.stderr)

    def _apply_stop_loss_take_profit(self, current_price: float, orders: OrderManager) -> None:
        """Apply stop loss and take profit on net position."""
        if self._position == 0:
            return
        entry = self._entry_price
        if entry == 0:
            return
        pnl_pct = (current_price - entry) / entry if self._position > 0 else (entry - current_price) / entry
        if pnl_pct <= -self.config.stop_loss_pct or pnl_pct >= self.config.take_profit_pct:
            side = "sell" if self._position > 0 else "buy"
            try:
                orders.place_market(side, abs(self._position))
                self._realized_pnl += self._position * (current_price - entry)
                self._position = 0.0
                self._entry_price = 0.0
            except Exception as e:
                print(f"[ERROR] Stop/take profit failed: {e}", file=sys.stderr)

    def on_tick(self, market: MarketData, orders: OrderManager) -> None:
        """Process market tick: update state, manage grid, handle risk."""
        try:
            timestamp = market.get_timestamp()
            price = market.get_price()
            volume = market.get_volume()
        except Exception as e:
            raise RuntimeError(f"Market data error: {e}") from e

        if price <= 0 or volume < 0:
            return

        # Append to history (bounded)
        self._price_history.append(price)
        self._volume_history.append(volume)
        max_hist = max(self.config.momentum_window, self.config.volatility_window) + 10
        if len(self._price_history) > max_hist:
            del self._price_history[:-max_hist]
            del self._volume_history[:-max_hist]
            gc.collect()

        # Initialize grid on first tick
        if not self._grid_levels:
            spacing = self._update_volatility()
            self._grid_levels = self._build_grid(price, spacing)
            self._place_grid_orders(orders, self._grid_levels)
            self._last_rebalance = timestamp
            self._entry_price = price
            return

        # Check stop loss / take profit
        self._apply_stop_loss_take_profit(price, orders)

        # Rebalance if needed
        if self._check_rebalance(timestamp, market):
            spacing = self._update_volatility()
            momentum = self._update_momentum()
            # Skip rebalance if strong counter-momentum
            if abs(momentum) > self.config.momentum_threshold:
                return
            self._cancel_all_orders(orders)
            self._grid_levels = self._build_grid(price, spacing)
            self._place_grid_orders(orders, self._grid_levels)
            self._last_rebalance = timestamp

    def on_fill(self, order_id: str, side: str, price: float, size: float) -> None:
        """Handle fill: update position, mark level filled, replace order."""
        # Find and mark level
        for level in self._grid_levels:
            if level.order_id == order_id:
                level.filled = True
                level.order_id = None
                break

        # Update position
        if side == "buy":
            if self._position <= 0:
                self._entry_price = price
            else:
                self._entry_price = (self._entry_price * self._position + price * size) / (self._position + size)
            self._position += size
        else:
            self._position -= size
            if self._position <= 0:
                self._entry_price = 0.0

        # Replace filled level with opposite side (grid logic)
        for level in self._grid_levels:
            if level.filled:
                new_side = "sell" if side == "buy" else "buy"
                new_price = price * (1 + self.config.base_spacing_pct if new_side == "sell" else -self.config.base_spacing_pct)
                level.side = new_side
                level.price = new_price
                level.filled = False
                level.size = self.config.capital_per_grid / new_price
                break


def generate_synthetic_data(n: int = 200, seed: int = 42) -> tuple[list[float], list[float], list[int]]:
    """Generate synthetic price/volume/timestamp data for testing."""
    rng = np.random.default_rng(seed)
    base = 100.0
    prices = []
    volumes = []
    timestamps = []
    for i in range(n):
        ret = rng.normal(0, 0.01)
        base *= (1 + ret)
        prices.append(base)
        volumes.append(float(rng.integers(100, 10000)))
        timestamps.append(1700000000 + i * 60)
    return prices, volumes, timestamps


class MockMarket:
    """Mock market data for testing."""

    def __init__(self, prices: list[float], volumes: list[float], timestamps: list[int]) -> None:
        self._prices = prices
        self._volumes = volumes
        self._timestamps = timestamps
        self._idx = 0

    def get_price(self) -> float:
        if self._idx >= len(self._prices):
            raise StopIteration
        return self._prices[self._idx]

    def get_volume(self) -> float:
        if self._idx >= len(self._volumes):
            raise StopIteration
        return self._volumes[self._idx]

    def get_timestamp(self) -> int:
        if self._idx >= len(self._timestamps):
            raise StopIteration
        return self._timestamps[self._idx]

    def next(self) -> None:
        self._idx += 1


class MockOrders:
    """Mock order manager for testing."""

    def __init__(self) -> None:
        self._orders: dict[str, dict[str, Any]] = {}
        self._counter = 0
        self.fills: list[tuple[str, str, float, float]] = []

    def place_limit(self, side: str, price: float, size: float) -> str:
        self._counter += 1
        oid = f"ord_{self._counter}"
        self._orders[oid] = {"side": side, "price": price, "size": size, "status": "open"}
        return oid

    def place_market(self, side: str, size: float) -> str:
        self._counter += 1
        oid = f"mkt_{self._counter}"
        self._orders[oid] = {"side": side, "size": size, "status": "filled"}
        return oid

    def cancel(self, order_id: str) -> bool:
        if order_id in self._orders:
            self._orders[order_id]["status"] = "cancelled"
            return True
        return False

    def get_open_orders(self) -> list[dict[str, Any]]:
        return [o for o in self._orders.values() if o.get("status") == "open"]

    def simulate_fill(self, order_id: str, price: float) -> None:
        if order_id in self._orders:
            order = self._orders[order_id]
            order["status"] = "filled"
            order["fill_price"] = price
            self.fills.append((order_id, order["side"], price, order["size"]))


if __name__ == "__main__":
    # Inline test with synthetic data
    print("=== AdaptiveGridMomentum Inline Test ===")

    config = GridConfig(
        symbol="TEST/EUR",
        base_spacing_pct=0.005,
        max_levels=10,
        capital_per_grid=5.0,
        momentum_window=20,
        momentum_threshold=0.002,
        volatility_window=30,
        min_spacing_pct=0.002,
        max_spacing_pct=0.015,
        rebalance_interval=60,
        stop_loss_pct=0.03,
        take_profit_pct=0.02,
        chunk_size=100,
    )

    strategy = AdaptiveGridMomentum(config)
    print(f"Memory estimate: {strategy.estimate_memory_mb():.4f} MB")

    prices, volumes, timestamps = generate_synthetic_data(150)
    market = MockMarket(prices, volumes, timestamps)
    orders = MockOrders()

    fills_processed = 0
    for i in range(len(prices)):
        strategy.on_tick(market, orders)

        # Simulate some fills randomly
        for oid, order in list(orders._orders.items()):
            if order.get("status") == "open" and np.random.random() < 0.05:
                orders.simulate_fill(oid, market.get_price())

        # Process fills
        for fill in orders.fills:
            if fill not in getattr(orders, "_processed_fills", []):
                strategy.on_fill(*fill)
                fills_processed += 1
        if not hasattr(orders, "_processed_fills"):
            orders._processed_fills = []
        orders._processed_fills.extend(orders.fills)

        market.next()

    print(f"Ticks processed: {len(prices)}")
    print(f"Fills processed: {fills_processed}")
    print(f"Final position: {strategy._position:.6f}")
    print(f"Realized PnL: {strategy._realized_pnl:.6f}")
    print(f"Grid levels active: {sum(1 for l in strategy._grid_levels if not l.filled)}")
    print("=== Test PASSED ===")
