"""
Regime-Persistence Vol-of-Vol Lattice with Equity-Gated Re-entry (RPVL-EGR)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1).
"""
from __future__ import annotations
import gc, math
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Dict, Iterator, List, Optional, Tuple

DEFAULT_CONFIG: Dict[str, Any] = {
    "symbol": "SOL/EUR", "capital": 13.5,
    "vol_fast_span": 7, "vol_slow_span": 32,
    "vvol_persist_floor": 1.0, "vvol_persist_ceil": 2.2,
    "base_levels": 7, "tight_levels": 11, "wide_levels": 5,
    "base_spacing_pct": 0.011, "spacing_scale_choppy": 0.55, "spacing_scale_sticky": 1.65,
    "ewm_returns_span": 48, "equity_drawdown_buffer": 0.045,
    "position_size_frac": 0.22, "fee": 0.0016, "stop_loss_frac": 0.10,
}

@dataclass
class EngineState:
    free_quote: float = 0.0
    total_equity: float = 0.0
    last_price: Optional[float] = None
    halt: bool = False
    regime: str = "neutral"
    levels: int = 0
    spacing: float = 0.0
    pending: Deque[float] = field(default_factory=deque)
    position_fills: int = 0
    realised_pnl: float = 0.0
    ewm_ret2_fast: float = 0.0
    ewm_ret2_slow: float = 0.0
    ewm_ret2: float = 0.0
    ewm_span: float = float(DEFAULT_CONFIG["ewm_returns_span"])
    ticks: int = 0
    equity_hwm: float = 0.0
    regime_stick: int = 0       # consecutive-tick regime dwell (hysteresis)

def _ewm_update(prev: float, new_val: float, span: float) -> float:
    if span <= 1.0: return new_val
    a = 2.0 / (span + 1.0)
    return a * new_val + (1.0 - a) * prev

class StrategyBase:
    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        cfg = DEFAULT_CONFIG.copy()
        if config: cfg.update(config)
        self.config = cfg
        self.state = EngineState(free_quote=float(cfg["capital"]), total_equity=float(cfg["capital"]), equity_hwm=float(cfg["capital"]))
        self.errors: List[str] = []

    def _ret2(self, price: float) -> float:
        last = self.state.last_price
        if last is None or last <= 0.0: return 0.0
        r = (price / last) - 1.0
        return r * r

    def _vvol_persist(self, r2: float) -> float:
        s = self.state
        s.ewm_ret2_fast = _ewm_update(s.ewm_ret2_fast, r2, float(self.config["vol_fast_span"]))
        s.ewm_ret2_slow = _ewm_update(s.ewm_ret2_slow, r2, float(self.config["vol_slow_span"]))
        s.ewm_ret2 = _ewm_update(s.ewm_ret2, r2, s.ewm_span)
        return s.ewm_ret2_fast / max(s.ewm_ret2_slow, 1e-12)

    def _anchor(self, price: float) -> float:
        base = math.sqrt(max(self.state.ewm_ret2, 1e-12))
        return price * (self.config["base_spacing_pct"] + base)

    def _pick_params(self, persist: float) -> Tuple[str, int, float]:
        c = self.config
        if persist >= c["vvol_persist_ceil"]: return "sticky", int(c["wide_levels"]), float(c["spacing_scale_sticky"])
        if persist <= c["vvol_persist_floor"]: return "choppy", int(c["tight_levels"]), float(c["spacing_scale_choppy"])
        return "neutral", int(c["base_levels"]), 1.0

    def _reshape(self, price: float) -> None:
        sp = self.state.spacing * self._anchor(price)
        n = self.state.levels
        self.state.pending = deque(sorted([price - i * sp for i in range(1, n + 1)]))

    def validate_config(self) -> List[str]:
        problems: List[str] = []
        c = self.config
        for k in ("capital", "base_levels", "tight_levels", "wide_levels"):
            if c.get(k, 0) <= 0: problems.append(k + " must be > 0")
        if c["tight_levels"] < c["wide_levels"]: problems.append("tight_levels must be >= wide_levels")
        for k in ("fee", "stop_loss_frac", "equity_drawdown_buffer"):
            if not (0.0 <= float(c[k]) < 1.0): problems.append(k + " must be in [0,1)")
        if c["vol_slow_span"] <= c["vol_fast_span"]: problems.append("vol_slow_span must exceed vol_fast_span")
        return problems

    def on_tick(self, price: float, timestamp: Optional[float] = None) -> Dict[str, Any]:
        p = float(price)
        if p <= 0.0: return {"action": "none", "reason": "non-positive_price"}
        s = self.state
        persist = self._vvol_persist(self._ret2(p))
        nr, nl, nsc = self._pick_params(persist)
        if s.last_price is None:
            s.regime, s.levels, s.spacing, s.regime_stick = nr, nl, nsc, 0
            self._reshape(p)
            s.last_price = p; s.ticks += 1
            return {"action": "seed", "regime": nr, "price": p}
        HYS = 3  # min consecutive ticks in a regime before flip is honoured
        if nr != s.regime:
            s.regime_stick += 1
        else:
            s.regime_stick = max(0, s.regime_stick - 1)
        if nr != s.regime and s.regime_stick >= HYS:
            s.regime, s.levels, s.spacing, s.regime_stick = nr, nl, nsc, 0
            self._reshape(p)
            s.last_price = p; s.ticks += 1
            return {"action": "reshape", "regime": nr, "price": p}
        s.equity_hwm = max(s.equity_hwm, s.total_equity)
        buf = float(self.config["equity_drawdown_buffer"])
        s.halt = s.total_equity < (s.equity_hwm * (1.0 - buf))
        if p < s.last_price * (1.0 - float(self.config["stop_loss_frac"])): s.halt = True
        fill = False
        if not s.halt and s.pending and p <= s.pending[0]:
            fill = True; s.pending.popleft()
            spend = min(s.total_equity * float(self.config["position_size_frac"]), s.free_quote)
            s.realised_pnl -= spend * float(self.config["fee"])
            s.free_quote -= spend; s.position_fills += 1
            s.pending.append(p - s.levels * s.spacing * self._anchor(p))
            s.pending = deque(sorted(s.pending))
        s.last_price = p; s.ticks += 1
        return {"action": "fill" if fill else "hold", "regime": s.regime, "price": p}

    def on_fill(self, price: float, qty: float) -> Dict[str, Any]:
        st = self.state; prev = st.total_equity
        st.total_equity += qty * price
        st.realised_pnl += (qty * price) * (1.0 - float(self.config["fee"]))
        st.equity_hwm = max(st.equity_hwm, st.total_equity)
        return {"accepted": True, "delta_pnl": st.total_equity - prev}

def estimate_memory_mb(config: Optional[Dict[str, Any]] = None) -> float:
    c = config or DEFAULT_CONFIG
    n = max(int(c["base_levels"]), int(c["tight_levels"]), int(c["wide_levels"]))
    return round((1500 + n * 96) / (1024 * 1024), 6)

def _stream(n: int, base: float = 100.0) -> Iterator[float]:
    # Directional walk: each regime block trends 12-15% with vol-of-vol swings,
    # so the grid lattice is crossed and fills fire on down-legs.
    seed = base; rl = max(n // 4, 1)
    drift = -0.0009  # slow bear drift overall
    for i in range(n):
        block = i // rl
        sticky = block % 2 == 0
        # regime-level swing: even blocks fast cracks, odd blocks slow recovery
        swing = 0.006 if sticky else -0.0032
        step = drift + swing * (1.0 if i % 2 else -1.0)
        seed = max(0.1, seed * (1.0 + step))
        if i % 50000 == 0 and i > 0: gc.collect()
        yield seed

if __name__ == "__main__":
    import time
    st = StrategyBase(dict(DEFAULT_CONFIG))
    bad = st.validate_config()
    if bad: raise SystemExit("config invalid: " + str(bad))
    print("estimate_memory_mb:", estimate_memory_mb())
    t0 = time.perf_counter()
    d: Dict[str, int] = {}
    for px in _stream(200_000):
        act = st.on_tick(px)["action"]
        d[act] = d.get(act, 0) + 1
    gc.collect()
    print("decisions:", d)
    print("pnl", round(st.state.realised_pnl, 4), "fills", st.state.position_fills, "regime", st.state.regime, "t", round(time.perf_counter() - t0, 2), "s")
    assert st.state.position_fills > 0
    assert d.get("reshape", 0) > 0
    print("OK - smoke test passed.")
