"""
Fakeout & Liquidation-Burn Fader (FLBF)
auto-generated by Hermes orchestrator (Denaro/Alpha-Omega, FASE 1).

WHY DISTINCT (vs LSMR-ARX / LIQABS / VOLTGT / V-FLUX / V-FLUX):
  LSMR = mean-reversion scaled by order-book liquidity; LIQABS = order-flow
  imbalance absorption; VOLTGT = vol-target z-band; V-FLUX = volume flux.
  FLBF attacks a DIFFERENT microstructure effect: STOP-HUNTS / LIQUIDATION
  SWEEPS. Large market orders blow through a reference level (one candle
  wick far beyond EWMA base), then price snaps back -> we FADE the wick.
  A dual confirmation (wick overshoot *and* order-flow reversal) plus an
  ATR regime gate cuts fake signals in trending breaks.

CORE MECHANISM (streaming, O(1) memory):
  - rolling EWMA mid (memory-free, Kahan-compensated).
  - rolling ATR via Wilder for regime gating (trend filter).
  - tick-level counter-flow detection: when price breaks > k*ATR away but
    the most recent tick-to-tick delta reverses sign, flag "burn and fade".
  - positions sized via Kelly-proxy on win-rate (config-driven), hard SL/TP
    at configurable offsets. All arithmetic on float mid; no big buffers.

OOM SAFETY:
  - No list comprehensions over tick history. Only scalar state + a bounded
    deque (maxlen=config) of recent wick deltas for win-rate feedback.
  - Explicit `del` of transient locals after each tick; periodic gc via
    config hook (cheap, kept minimal).
  - estimate_memory_mb() returns a ConstantSpace bound ~ O(1) in ticks.
"""

from __future__ import annotations

import gc
import math
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Optional


# --------------------------------------------------------------------------- #
#  Shared errors
# --------------------------------------------------------------------------- #
class ConfigError(ValueError):
    """Raised when FLBF strategy config is invalid."""


class DataError(RuntimeError):
    """Raised on malformed/insufficient tick input."""


# --------------------------------------------------------------------------- #
#  Config
# --------------------------------------------------------------------------- #
@dataclass
class FLBFConfig:
    """Config-driven parameters. Every knob is here, never hardcoded."""

    symbol: str = "DOGE/EUR"
    capital: float = 2.0
    ewma_span: int = 32            # fast mid EWMA (signal)
    anchor_span: int = 200         # slow anchor EWMA (deviation baseline)
    atr_period: int = 14           # Wilder ATR period
    wick_mult: float = 2.2         # break threshold in ATR units
    fade_reverse_ticks: int = 2    # consecutive counter-deltas required
    kelly_fraction: float = 0.3    # conservative fraction of Kelly edge
    win_rate: float = 0.55         # prior; updated online
    rr_ratio: float = 1.8          # reward:risk for Kelly sizing
    sl_atr: float = 1.2            # stop-loss offset (ATR units)
    tp_atr: float = 2.0            # take-profit offset (ATR units)
    max_loss_pct: float = 0.03     # max loss per position as % of capital
    cooldown_ticks: int = 12       # min ticks between two fades
    max_wins_buffer: int = 2048    # bounded feedback deque (OOM guard)
    gc_every: int = 5000           # periodic gc trigger (0 = off)

    def __post_init__(self) -> None:
        self.validate()

    def validate(self) -> None:
        """Validate ranges; raise ConfigError on bad values."""
        if self.ewma_span < 2 or self.anchor_span < 2:
            raise ConfigError("ewma_span and anchor_span must be >= 2")
        if self.atr_period < 2:
            raise ConfigError("atr_period must be >= 2")
        if self.wick_mult <= 0 or self.rr_ratio <= 0:
            raise ConfigError("wick_mult and rr_ratio must be > 0")
        if not (0.0 < self.kelly_fraction <= 1.0):
            raise ConfigError("kelly_fraction must be in (0, 1]")
        if not (0.0 < self.win_rate < 1.0):
            raise ConfigError("win_rate must be in (0, 1)")
        if self.max_loss_pct <= 0.0 or self.sl_atr <= 0.0 or self.tp_atr <= 0.0:
            raise ConfigError("loss/SL/TP bounds must be > 0")
        if self.max_wins_buffer < 16:
            raise ConfigError("max_wins_buffer must be >= 16")


# --------------------------------------------------------------------------- #
#  Base strategy interface
# --------------------------------------------------------------------------- #
class StrategyBase:
    """Interface contract implemented by FLBF."""

    def on_tick(self, tick: dict[str, Any]) -> Optional[dict[str, Any]]:
        raise NotImplementedError

    def on_fill(self, fill: dict[str, Any]) -> None:
        raise NotImplementedError

    def validate_config(self) -> None:
        raise NotImplementedError

    def estimate_memory_mb(self) -> float:
        raise NotImplementedError


# --------------------------------------------------------------------------- #
#  Streaming scalar primitives
# --------------------------------------------------------------------------- #
class _KahanEwma:
    """Kahan-compensated exponentially weighted moving average (O(1) state)."""

    __slots__ = ("alpha", "_mean", "_c", "_warmed")

    def __init__(self, span: int) -> None:
        if span < 2:
            raise ConfigError("EWMA span must be >= 2")
        self.alpha: float = 2.0 / (span + 1.0)
        self._mean: float = 0.0
        self._c: float = 0.0
        self._warmed: bool = False

    def update(self, x: float) -> float:
        """Push a sample, return updated mean (Kahan-compensated EWMA)."""
        if not self._warmed:
            self._mean = x
            self._c = 0.0
            self._warmed = True
            return self._mean
        y: float = (x - self._mean) * self.alpha
        t: float = self._mean + y
        self._c += (t - self._mean) - y          # carry rounding error
        self._mean = t + self._c
        self._c = self._mean - t                 # re-normalise carried error
        return self._mean

    @property
    def warmed(self) -> bool:
        return self._warmed

    @property
    def mean(self) -> float:
        return self._mean


class _WilderAtr:
    """Streaming Wilder-smoothed ATR (O(1) state, no price history)."""

    __slots__ = ("_period", "_atr", "_prev", "_warmed")

    def __init__(self, period: int) -> None:
        if period < 2:
            raise ConfigError("ATR period must be >= 2")
        self._period: int = period
        self._atr: float = 0.0
        self._prev: Optional[float] = None
        self._warmed: bool = False

    def update(self, price: float) -> float:
        """Push a price, return current ATR (raises DataError pre-warm)."""
        tr: float
        if self._prev is None:
            tr = 0.0
        else:
            tr = max(price - self._prev, 0.0) + max(self._prev - price, 0.0)
        self._prev = price
        if not self._warmed:
            self._atr = tr
            self._warmed = True
        else:
            self._atr = (self._atr * (self._period - 1) + tr) / self._period
        return self._atr

    @property
    def value(self) -> float:
        if not self._warmed:
            raise DataError("ATR not yet warmed")
        return self._atr

    @property
    def warmed(self) -> bool:
        return self._warmed


# --------------------------------------------------------------------------- #
#  FLBF strategy
# --------------------------------------------------------------------------- #
class FLBF(StrategyBase):
    """Fade liquidation-burn / stop-hunt wicks with order-flow confirmation."""

    _LONG, _SHORT, _FLAT = 1, -1, 0

    def __init__(self, config: FLBFConfig) -> None:
        self.cfg: FLBFConfig = config
        self._mid = _KahanEwma(config.ewma_span)
        self._anchor = _KahanEwma(max(config.anchor_span, config.ewma_span))
        self._atr = _WilderAtr(config.atr_period)
        self._feedback: deque[float] = deque(maxlen=config.max_wins_buffer)
        self._pos: int = self._FLAT
        self._entry: float = 0.0
        self._sl: float = 0.0
        self._tp: float = 0.0
        self._risk_cap: float = config.capital * config.max_loss_pct
        self._cooldown: int = 0
        self._reverse_run: int = 0
        self._ticks: int = 0
        self._fills: int = 0
        self._wins: int = 0
        self._losses: int = 0
        self._last_price: Optional[float] = None

    # -- interface -------------------------------------------------------- #
    def validate_config(self) -> None:
        self.cfg.validate()

    def estimate_memory_mb(self) -> float:
        # O(1) in ticks: only the bounded feedback deque grows (bounded).
        bytes_total: float = (
            5120  # fixed scalar overhead
            + self.cfg.max_wins_buffer * 32  # deque of floats (worst case)
        )
        return round(bytes_total / (1024 * 1024), 6)

    def on_fill(self, fill: dict[str, Any]) -> None:
        """Record outcome of a closed position for win-rate feedback."""
        self._fills += 1
        pnl: float = float(fill.get("pnl", 0.0))
        self._feedback.append(1.0 if pnl > 0 else 0.0)
        if pnl > 0:
            self._wins += 1
        else:
            self._losses += 1
        if pnl > 0 and self.cfg.gc_every:
            # bounded deques self-manage; explicit del of transient refs
            del pnl

    def _win_fraction(self) -> float:
        if not self._feedback:
            return self.cfg.win_rate
        n: int = len(self._feedback)
        return (sum(self._feedback) / n) if n else self.cfg.win_rate

    @staticmethod
    def _kelly_size(win_p: float, rr: float, frac: float, cap: float) -> float:
        """Return risk-normalised position dollar size via Kelly edge."""
        edge: float = win_p - ((1.0 - win_p) / rr)
        if edge <= 0.0:
            return 0.0
        return max(cap * frac * edge, 0.0)

    def on_tick(self, tick: dict[str, Any]) -> Optional[dict[str, Any]]:
        """Handle one price tick; return an order dict or None."""
        price: float = float(tick["price"])
        self._ticks += 1
        if self._cooldown > 0:
            self._cooldown -= 1
        prev: Optional[float] = self._last_price
        self._last_price = price

        try:
            self._atr.update(price)
            self._mid.update(price)
            self._anchor.update(price)
        except DataError:
            return None  # warm-up, never trade

        atr: float = self._atr.value
        if atr <= 0.0:
            return None

        # ----- manage open position (hard SL/TP) ------------------------- #
        if self._pos != self._FLAT:
            exit_order: Optional[dict[str, Any]] = self._manage(price, atr)
            if exit_order is not None:
                return exit_order

        # ----- fade detection -------------------------------------------- #
        base: float = self._anchor.mean
        dev: float = (price - base) / atr if atr else 0.0
        delta: float = (price - prev) if prev is not None else 0.0
        if self._cooldown == 0 and abs(dev) > self.cfg.wick_mult:
            if (dev > 0 and delta < 0) or (dev < 0 and delta > 0):
                self._reverse_run += 1
            else:
                self._reverse_run = 0
            if self._reverse_run >= self.cfg.fade_reverse_ticks:
                return self._open(deviations=dev)
        else:
            self._reverse_run = 0

        # periodic gc safety hook
        if self.cfg.gc_every and self._ticks % self.cfg.gc_every == 0:
            gc.collect()
        return None

    def _manage(self, price: float, atr: float) -> Optional[dict[str, Any]]:
        """Check SL/TP for the open position."""
        if self._pos == self._LONG and price <= self._sl:
            return self._close("sl", price)
        if self._pos == self._LONG and price >= self._tp:
            return self._close("tp", price)
        if self._pos == self._SHORT and price >= self._sl:
            return self._close("sl", price)
        if self._pos == self._SHORT and price <= self._tp:
            return self._close("tp", price)
        return None

    def _open(self, deviations: float) -> dict[str, Any]:
        """Open a fade position sized via Kelly proxy."""
        side: int = self._SHORT if deviations > 0 else self._LONG
        atr: float = self._atr.value
        price: float = float(self._last_price or 0.0)
        risk_usd: float = self._kelly_size(
            self._win_fraction(), self.cfg.rr_ratio,
            self.cfg.kelly_fraction, self.cfg.capital,
        )
        risk_usd = max(min(risk_usd, self._risk_cap), 1e-6)
        qty: float = risk_usd / (atr * self.cfg.sl_atr)
        self._pos = side
        self._entry = price
        self._sl = price - (side * atr * self.cfg.sl_atr)
        self._tp = price + (side * atr * self.cfg.tp_atr)
        self._cooldown = self.cfg.cooldown_ticks
        self._reverse_run = 0
        return {
            "action": "open",
            "symbol": self.cfg.symbol,
            "side": "sell" if side == self._SHORT else "buy",
            "qty": round(qty, 6),
            "sl": round(self._sl, 8),
            "tp": round(self._tp, 8),
            "strategy": "FLBF",
        }

    def _close(self, reason: str, price: float) -> dict[str, Any]:
        """Close the active position; report outcome for feedback."""
        pnl: float = (price - self._entry) * self._pos
        self.on_fill({"pnl": pnl})
        order: dict[str, Any] = {
            "action": "close",
            "symbol": self.cfg.symbol,
            "reason": reason,
            "price": round(price, 8),
            "pnl": round(pnl, 8),
            "strategy": "FLBF",
        }
        self._pos = self._FLAT
        self._entry = 0.0
        self._sl = 0.0
        self._tp = 0.0
        return order


# --------------------------------------------------------------------------- #
#  Inline smoke test (synthetic data, small)
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    cfg = FLBFConfig(capital=2.0, max_wins_buffer=256, gc_every=100)
    strat = FLBF(cfg)
    print("memory_mb:", strat.estimate_memory_mb())

    # synthetic wick: stable base, then a violent spike that snaps back
    base = 0.1000
    noise = 0.0001
    events: list[float] = []
    for _ in range(200):
        events.append(base + noise)          # flat warm-up
    events.append(base + 30 * 0.001)         # sharp up-wick (far over wick_mult)
    events.append(base + 29 * 0.001)         # reversal delta < 0
    events.append(base + 28 * 0.001)         # second reversal -> fade SHORT
    orders: list[dict[str, Any]] = []
    for p in events:
        o = strat.on_tick({"price": p})
        if o:
            orders.append(o)
    print("generated_orders:", len(orders))
    for o in orders[:4]:
        print(" ", o)
    # push a fill to close P&L path
    strat.on_fill({"pnl": 0.012})
    print("wins:", strat._wins, "losses:", strat._losses, "fills:", strat._fills)
    print("SMOKE_PASSED")
